'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const session = document.querySelector('meta[name="arwen-session"]').content;
let state = {view:'home',step:0,tab:'overview',draft:null,inspection:null,saved:'',path:'',dirty:false,job:null,domain:0,externalKind:'met-em'};
let options, catalog, timer, busy=false;
let camera={x:0,y:0,w:720,h:360};
let form={name:'Regional forecast',lat:35.3,lon:-97.5,width:900,height:700,dx:12,nz:49,hours:6,history:720,chain:'',tiles:'off',vram:'',profile:''};
const starters=[{id:'regional',name:'Regional outlook',subtitle:'One domain for a regional forecast.',spec:'12 km · 6 hours · 1 domain',icon:'◎',values:{name:'Regional forecast',width:900,height:700,dx:12,hours:6,chain:''}},
 {id:'local',name:'Local detail',subtitle:'A regional grid with a finer nested domain.',spec:'9 → 3 km · 3 hours · 2 domains',icon:'▣',values:{name:'Local forecast',width:180,height:150,dx:9,hours:3,chain:'3'}},
 {id:'custom',name:'Your own setup',subtitle:'Set your own region, spacing and physics.',spec:'Editable region, grid & physics',icon:'⌁',values:{name:'Custom forecast',width:400,height:300,dx:12,hours:6,chain:''}}];
async function api(action, payload={}) {
 const response=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-Arwen-Session':session},body:JSON.stringify({action,...payload})});
 const result=await response.json();if(!result.ok)throw Error(result.error||'The local engine could not complete this request.');return result.value;
}
function notice(message,success=false){$('notice').hidden=!message;$('notice').className=success?'success':'';$('notice').textContent=message;if(message){let close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Dismiss message');close.onclick=()=>notice('');$('notice').prepend(close);}}
let taskQueue=Promise.resolve();
function task(button,callback){if(button){button.disabled=true;button.dataset.before=button.textContent;button.textContent='Working…';}const run=async()=>{notice('');try{await callback();}catch(e){notice(e.message);}finally{if(button&&button.isConnected){button.disabled=false;button.textContent=button.dataset.before;}}};taskQueue=taskQueue.then(run,run);return taskQueue;}
function goHome(){if(state.dirty&&!confirm('Keep this unsaved draft? Choose Cancel to stay, or OK to return home. The draft remains in this window.'))return;state.view='home';render();}
$('home-link').onclick=e=>{e.preventDefault();goHome();};
$('system-button').onclick=e=>task(e.currentTarget,async()=>{state.job=await api('start',{mode:'doctor'});render();poll();});
function field(label,id,value,type='text',help='',extra=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}>${help?`<span class="help">${help}</span>`:''}</div>`;}
function select(label,id,value,items,help=''){return `<div class="field"><label for="${id}">${label}</label><select id="${id}">${items.map(([v,t])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select>${help?`<span class="help">${help}</span>`:''}</div>`;}
function control(label,id,value,min,max,step,unit){return `<div class="field"><label for="${id}">${label}<span class="control-unit">${unit}</span></label><div class="control"><div class="knob" id="${id}-knob" role="spinbutton" tabindex="0" aria-label="${label} dial" aria-valuenow="${value}" aria-valuetext="${value} ${unit}" data-unit="${unit}" title="Drag up or down, or use arrow keys. Shift makes a finer adjustment."><span class="knob-cap" aria-hidden="true"></span></div><div class="slider-scale"><input aria-label="${label} slider" id="${id}-slider" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><span aria-hidden="true">${min}<i></i>${max} ${unit}</span></div><input aria-label="${label} exact value" id="${id}" type="number" step="any" value="${value}"></div><span class="dial-help">Drag dial or use ↑ / ↓ · exact entry at right</span></div>`;}
// Decimal addition keeps a dial step from introducing a displayed binary tail
// or rounding away precision that the user entered in the numeric control.
function decimalAdd(value,delta,steps=1,shift=0){
 const parts=x=>{const [m,e='0']=String(x).toLowerCase().split('e'),[whole,fraction='']=m.split('.');return {n:BigInt(whole+fraction),scale:fraction.length-Number(e)};};
 const a=parts(value),b=parts(delta);b.n*=BigInt(steps);b.scale+=shift;const scale=Math.max(a.scale,b.scale,0);
 let n=a.n*10n**BigInt(scale-a.scale)+b.n*10n**BigInt(scale-b.scale);
 const sign=n<0n?'-':'';let digits=(n<0n?-n:n).toString().padStart(scale+1,'0');
 return sign+(scale?digits.slice(0,-scale)+'.'+digits.slice(-scale):digits);
}
function bindControl(id, callback){
 const n=$(id),slider=$(id+'-slider'),knob=$(id+'-knob');if(!n)return;
 function change(source){
  const v=Number(source.value);if(source===n)slider.value=v;else n.value=source.value;
  if(Number.isFinite(v)&&n.value!==''){
   const position=Math.max(0,Math.min(1,(v-Number(slider.min))/(Number(slider.max)-Number(slider.min))));
   knob.style.setProperty('--angle',(-120+240*position)+'deg');
   knob.setAttribute('aria-valuenow',n.value);knob.setAttribute('aria-valuetext',`${n.value} ${knob.dataset.unit}`);
  }
  callback(v);
 }
 function adjust(steps,fine=false){
  if(!Number.isFinite(Number(n.value))||!n.value)return;
  n.value=decimalAdd(n.value,slider.step,steps,fine?1:0);change(n);
 }
 n.oninput=()=>change(n);slider.oninput=()=>change(slider);
 knob.onkeydown=e=>{const steps={ArrowUp:1,ArrowRight:1,ArrowDown:-1,ArrowLeft:-1,PageUp:10,PageDown:-10}[e.key];if(steps){e.preventDefault();adjust(steps,e.shiftKey);}};
 let drag=null;
 knob.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();knob.focus();drag={y:e.clientY};knob.classList.add('adjusting');knob.setPointerCapture(e.pointerId);};
 knob.onpointermove=e=>{if(!drag)return;const steps=Math.trunc((drag.y-e.clientY)/5);if(steps){adjust(steps,e.shiftKey);drag.y-=steps*5;}};
 const release=()=>{drag=null;knob.classList.remove('adjusting');};
 knob.onpointerup=release;knob.onpointercancel=release;knob.onlostpointercapture=release;
 // Paint the readout without changing an imported or out-of-slider-range value.
 const position=Math.max(0,Math.min(1,(Number(n.value)-Number(slider.min))/(Number(slider.max)-Number(slider.min))));
 knob.style.setProperty('--angle',(-120+240*position)+'deg');
}
let geography=null, geographyMarkup='', placeIndex=[], placeQuery='', geographyError='';
const foldPlace=s=>String(s).normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase();
function paintGeography(){const group=$('geography');if(!group||!geography)return;if(!group.firstChild)group.innerHTML=geographyMarkup;const overview=$('overview-map');if(overview)overview.style.display='none';}
function placeSearchMarkup(){return `<div class="place-search"><div class="field"><label for="place-search">Find a city or town</label><input id="place-search" type="search" autocomplete="off" value="${esc(placeQuery)}" placeholder="Name, region or country" aria-describedby="place-help"><span class="help" id="place-help">${geographyError||'Offline place catalog. Select a result to center your region; exact coordinates remain available.'}</span></div><div id="place-results" class="place-results" aria-live="polite"></div></div>`;}
function showPlaceResults(){
 const results=$('place-results');if(!results)return;const q=foldPlace($('place-search').value.trim());placeQuery=$('place-search').value;
 if(q.length<2){results.replaceChildren();return;}
 if(!geography){results.textContent=geographyError||'Loading the offline place catalog…';return;}
 const words=q.split(/\s+/),matches=placeIndex.filter(p=>words.every(w=>p.key.includes(w))).sort((a,b)=>(a.name===q?-2:a.name.startsWith(q)?-1:0)-(b.name===q?-2:b.name.startsWith(q)?-1:0)).slice(0,12);
 if(!matches.length){results.textContent='No match in this catalog. Enter coordinates or pan the map.';return;}
 results.innerHTML=matches.map(({row})=>`<button type="button" data-place="${row[0]}"><strong>${esc(row[1])}</strong><span>${esc(row[3])} · ${esc(row[4])}</span><small>${row[6]}°, ${row[7]}°</small></button>`).join('');
 results.querySelectorAll('[data-place]').forEach(button=>button.onclick=()=>{const row=matches.find(p=>p.row[0]===Number(button.dataset.place)).row;form.lat=row[6];form.lon=row[7];$('lat').value=form.lat;$('lon').value=form.lon;placeQuery=`${row[1]}, ${row[3]}, ${row[4]}`;$('place-search').value=placeQuery;results.replaceChildren();$('place-help').textContent=`Region centered on ${row[1]} · ${row[3]}, ${row[4]}. Width, spacing and physics are unchanged.`;fitRegion();});
}
function clearPlaceSelection(){placeQuery='';if($('place-search'))$('place-search').value='';if($('place-results'))$('place-results').replaceChildren();if($('place-help'))$('place-help').textContent='Coordinates set directly. Search again to center on a catalog place.';}
function bindPlaceSearch(){const input=$('place-search');if(!input)return;input.oninput=showPlaceResults;input.onkeydown=e=>{if(e.key==='ArrowDown'){const first=$('place-results').querySelector('button');if(first){e.preventDefault();first.focus();}}if(e.key==='Escape')$('place-results').replaceChildren();};}
function drawPlaces(){
 const labels=$('place-labels');if(!labels||!geography)return;
 const svg=$('map-overlay'),width=svg.clientWidth,height=svg.clientHeight;if(!width||!height)return;
 const middle=(camera.x+camera.w/2)/2-180,boxes=[],chosen=[];
 for(const row of geography.places){
  const x=(((row[7]-middle+540)%360-180+middle+180)*2-camera.x)/camera.w*width,y=((90-row[6])*2-camera.y)/camera.h*height;
  if(x<12||x>width-12||y<42||y>height-32)continue;
  const labelWidth=Math.min(row[1].length*6.5,150),box=[x+5,y-12,x+labelWidth+9,y+4];
  if(box[2]>width-10||boxes.some(b=>box[0]<b[2]+8&&box[2]>b[0]-8&&box[1]<b[3]+5&&box[3]>b[1]-5))continue;
  boxes.push(box);chosen.push(`<g transform="translate(${camera.x+x/width*camera.w},${camera.y+y/height*camera.h})"><circle r="${2*camera.w/width}"/><text x="${5*camera.w/width}" y="${-2*camera.h/height}" font-size="${11*camera.w/width}">${esc(row[1])}</text></g>`);
  if(chosen.length===30)break; // display decluttering only; search retains every place
 }
 labels.innerHTML=chosen.join('');
}
window.addEventListener('resize',()=>{$('region-map')?.onpointercancel?.();drawMap();});
async function loadGeography(){try{
 const response=await fetch('/geography.json');if(!response.ok)throw Error('Offline geography could not be read.');
 const data=await response.json();if(data.schema!=='arwen.offline-geography.v1')throw Error('Unknown offline geography schema.');
 geography=data;placeIndex=data.places.map(row=>({row,name:foldPlace(row[1]),key:foldPlace([row[1],row[2],row[3],row[4],row[5],row[9]].join(' '))}));
 geographyMarkup='<defs><g id="geography-shapes">'+[['land','land','#233321','#7b9260',.75],['lakes','lakes','#0c1c15','#789965',.7],['boundaries','provinces','none','#8b9e72',.65],['countries','countries','none','#b5c18e',1]].map(([key,kind,fill,stroke,line])=>`<g class="${kind}" fill="${fill}" stroke="${stroke}" stroke-width="${line}" fill-rule="evenodd">${data[key].map(d=>`<path d="${d}" vector-effect="non-scaling-stroke"/>`).join('')}</g>`).join('')+'</g></defs><use href="#geography-shapes"/><use href="#geography-shapes" transform="translate(-720,0)"/><use href="#geography-shapes" transform="translate(720,0)"/>';
 paintGeography();drawMap();if($('place-search'))showPlaceResults();
}catch(e){geographyError='Offline place catalog unavailable. Exact coordinates and the overview map still work.';if($('place-help'))$('place-help').textContent=geographyError;}}
function mapMarkup(interactive=false){return `<div class="map" id="region-map"><svg class="overlay" id="map-overlay" viewBox="${camera.x} ${camera.y} ${camera.w} ${camera.h}" preserveAspectRatio="none" aria-label="${state.view==='editor'?'Actual projected domain footprints':'Requested geographic rectangle preview'}"><image id="overview-map" href="/world.svg" x="0" y="0" width="720" height="360"/><g id="geography"></g><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#84ac58" stroke-width=".5" vector-effect="non-scaling-stroke" opacity=".35"/></pattern></defs><rect width="720" height="360" fill="url(#grid)"/><g id="place-labels"></g><g id="footprint"></g></svg><div class="radar-corner">${state.view==='editor'?'CONFIGURED GRID / PROJECTED':'REQUESTED REGION / APPROXIMATE'}</div><div class="map-callout">NO WEATHER OVERLAY</div><div class="map-label"><span id="coord-label"></span><span>${interactive?'CLICK TO CENTER · DRAG TO PAN':'DRAG TO PAN'}</span></div></div><div class="map-toolbar"><button class="quiet small" id="zoom-in" aria-label="Zoom in">+</button><button class="quiet small" id="zoom-out" aria-label="Zoom out">−</button><button class="quiet small" id="fit-region">Fit region</button><button class="quiet small" id="world-view">World</button><span>Natural Earth + GeoNames · <a href="/geography-sources" target="_blank" rel="noopener">map sources</a></span></div>`;}
function requestedPoints(){const w=form.width/111.32/Math.cos(form.lat*Math.PI/180),h=form.height/111.32;return [[form.lon-w/2,form.lat-h/2],[form.lon+w/2,form.lat-h/2],[form.lon+w/2,form.lat+h/2],[form.lon-w/2,form.lat+h/2]];}
function mapPoints(){return state.view==='editor'?(state.inspection.footprints||[]):[requestedPoints()];}
function mapAspect(){const box=$('map-overlay')?.getBoundingClientRect();return box?.width>0&&box?.height>0?box.width/box.height:2;}
function fitMapBounds(x0,y0,x1,y1,padding=1){const aspect=mapAspect(),width=Math.max(x1-x0,(y1-y0)*aspect,.1)*padding,height=width/aspect;camera={x:(x0+x1-width)/2,y:(y0+y1-height)/2,w:width,h:height};drawMap();}
function fitRegion(){const pts=mapPoints().flat();if(!pts.length)return;const lon0=pts[0][0];const x=pts.map(p=>((p[0]-lon0+540)%360-180+lon0+180)*2),y=pts.map(p=>(90-p[1])*2);fitMapBounds(Math.min(...x),Math.min(...y),Math.max(...x),Math.max(...y),1.5);}
function drawMap(){const group=$('footprint');if(!group)return;const height=camera.w/mapAspect();camera.y+=(camera.h-height)/2;camera.h=height;paintGeography();const mid=(camera.x+camera.w/2)/2-180;const paths=mapPoints();group.innerHTML=paths.map((pts,i)=>{const p=pts.map(([lon,lat])=>`${((lon-mid+540)%360-180+mid+180)*2},${(90-lat)*2}`).join(' ');return `<polygon points="${p}" fill="#b6f47619" stroke="${i?'#e4efad':'#bdf578'}" stroke-width="${camera.w/420}"/><text x="${((pts[0][0]-mid+540)%360-180+mid+180)*2}" y="${(90-pts[0][1])*2-camera.h/45}" fill="#c7eda6" font-family="Consolas,monospace" font-size="${camera.w/55}">${state.view==='editor'?'d'+String(i+1).padStart(2,'0'):''}</text>`;}).join('');$('map-overlay').setAttribute('viewBox',`${camera.x} ${camera.y} ${camera.w} ${camera.h}`);$('coord-label').textContent=state.view==='editor'?'ACTUAL PROJECTED CELL EDGES':`${Math.abs(form.lat).toFixed(2)}° ${form.lat<0?'S':'N'} / ${Math.abs(form.lon).toFixed(2)}° ${form.lon<0?'W':'E'}`;drawPlaces();}
function bindMap(){if(!$('region-map'))return;function zoom(f){camera.x+=camera.w*(1-f)/2;camera.y+=camera.h*(1-f)/2;camera.w*=f;camera.h*=f;drawMap();}$('zoom-in').onclick=()=>zoom(.5);$('zoom-out').onclick=()=>zoom(2);$('fit-region').onclick=fitRegion;$('world-view').onclick=()=>fitMapBounds(0,0,720,360);const map=$('region-map');let down;
 map.onpointercancel=map.onlostpointercapture=()=>{down=null;};
 map.onpointerdown=e=>{if(e.button!==0)return;down={x:e.clientX,y:e.clientY,c:{...camera}};map.setPointerCapture(e.pointerId);};
 map.onpointermove=e=>{if(!down)return;const r=map.getBoundingClientRect();camera.x=down.c.x-(e.clientX-down.x)/r.width*camera.w;camera.y=down.c.y-(e.clientY-down.y)/r.height*camera.h;drawMap();};
 map.onpointerup=e=>{if(!down)return;if(state.view==='builder'&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5){const r=map.getBoundingClientRect();const latitude=+(90-(camera.y+(e.clientY-r.top)/r.height*camera.h)/2).toFixed(4);if(latitude<=-90||latitude>=90){down=null;return;}form.lon=+(((camera.x+(e.clientX-r.left)/r.width*camera.w)/2-180+540)%360-180).toFixed(4);form.lat=latitude;if($('lat'))$('lat').value=form.lat;if($('lon'))$('lon').value=form.lon;clearPlaceSelection();drawMap();}down=null;};}
function schemeName(key,value){for(const c of Object.values(catalog.components))for(const o of Object.values(c.options||{}))if(o.selectors?.[key]===Number(value))return o.label;return String(value??'Config');}
function humanPlan(){if(!state.planSnapshot)return '';const raw=state.planSnapshot.document,exp=raw.experiment||{},source=raw.fetch?.source||raw.case_data?.source||'Declared inputs';return `<div class="human-plan"><div><small>Forcing / start</small><strong>${esc(source.toUpperCase())} · ${esc(exp.start_time)}</strong></div><div><small>Domains / run</small><strong>${(raw.domain||[]).map(d=>`${d.nx} × ${d.ny}`).join(' / ')} · ${exp.run_seconds/3600} hours</strong></div><div><small>Requested microphysics / surface</small><strong>${esc(schemeName('mp_physics',raw.domain?.[0]?.mp_physics??raw.shared?.mp_physics))} / ${esc(schemeName('sf_surface_physics',raw.domain?.[0]?.sf_surface_physics??raw.shared?.sf_surface_physics))}</strong></div><div><small>Output</small><strong class="path-wrap">${esc(state.planSnapshot.output)}</strong></div></div>`;}
function jobMarkup(){if(!state.job||!state.job.command?.length)return '';let j=state.job,plan=j.action==='go'&&j.command.includes('--dry-run'),forecast=(j.action==='go'&&!plan)||(j.action==='sim'&&!j.command.includes('--print-command'))||j.action==='run',heading=j.poll_error?'Process status needs attention':j.active?'Command in progress':j.exit_code===0?(plan?'Launch plan ready':forecast?'Forecast complete':'Command completed'):'Command needs attention';const lines=(j.log||'').split('\n').map(x=>x.trim()).filter(Boolean);const live=lines.filter(x=>x.startsWith('go: ')).slice(-1)[0];const stage=live?(live.includes('stepping:')?'Forecast advancing':live.slice(4).replaceAll('-',' ')):'';const failure=j.exit_code!==0&&!j.active?lines.filter(x=>!x.startsWith('{')).slice(-1)[0]:'';return `<section class="job" id="job"><div class="job-head"><div><h3><span class="job-light ${j.active?'running':j.exit_code===0?'':'failed'}"></span>${heading}</h3><p>${esc(j.poll_error||failure||(j.active?(stage||'Starting command')+'. Logs are retained; closing the browser keeps it running.':plan?'The plan is ready. Check readiness, then Prepare & run when you are ready.':'The command returned success. Its full details remain available.'))}</p></div>${j.active?'<button id="stop" class="danger small">Stop this command</button>':'<span class="pill">EXIT '+j.exit_code+'</span>'}</div>${plan?humanPlan():''}${j.output?`<div class="result-location"><div><small>${forecast&&!j.active&&j.exit_code===0?'Forecast results':'Output folder'}</small><p class="mono">${esc(j.output)}</p></div><button class="primary small" id="open-results">Open results ↗</button></div>`:''}<details><summary>Technical details · exact command and saved log</summary><div class="job-command">${j.command.map(esc).join(' ')}</div><pre id="job-log">${esc(j.log||'Waiting for the first output…')}</pre><div class="status-line">Log folder: <span class="mono">${esc(j.folder)}</span></div></details></section>`;}
function home(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">ARWEN / LOCAL OPERATIONS</div><h1>Forecast console</h1><p>Start with a preset, or bring an ArWen, WRF or WPS configuration.</p><ol class="console-sequence"><li><b>01</b><div><strong>Select</strong><span>Preset or existing inputs</span></div></li><li><b>02</b><div><strong>Configure</strong><span>Region, grid, physics & output</span></div></li><li><b>03</b><div><strong>Launch</strong><span>Review the plan, then run</span></div></li></ol></div><div class="hero-console"><div class="console-label"><span><i></i> REGION DISPLAY</span><span>OFFLINE GEOGRAPHY</span></div>${mapMarkup()}<div class="console-readouts"><div><small>Requested area</small><strong>${form.width} × ${form.height}<em> km</em></strong></div><div><small>Root spacing</small><strong>${form.dx}<em> km</em></strong></div><div><small>Forecast length</small><strong>${form.hours}<em> h</em></strong></div></div></div></section><div class="section-head"><h2>Choose a starting point</h2><span>EVERY SETTING IS EDITABLE</span></div><section class="presets">${starters.map((p,i)=>`<button class="preset" data-preset="${p.id}"><div class="card-head"><span class="card-number">CONFIG / 0${i+1}</span><span class="card-icon" aria-hidden="true">${p.icon}</span></div><div class="card-body"><h3>${p.name}</h3><p>${p.subtitle}</p><div class="card-foot"><span>${p.spec}</span><b>↗</b></div></div></button>`).join('')}</section><section class="imports"><button class="import-card" id="import-config"><span class="import-symbol">↳</span><div><h3>Import an ArWen configuration</h3><p>Open your TOML. Keep its comments and complete settings.</p></div><span class="arrow">→</span></button><button class="import-card" id="external-inputs"><span class="import-symbol">▤</span><div><h3>Use WRF inputs or WPS met_em</h3><p>Bring an existing namelist and prepared input directory.</p></div><span class="arrow">→</span></button></section><p class="home-note"><b>○</b> Nothing downloads or runs until you ask. Presets are starting points, not restrictions.</p>${state.draft?'<p class="home-note"><button class="quiet small" id="return-draft">Return to your open forecast</button></p>':''}${jobMarkup()}`;}
function builder(){const profiles=[['','Source recommendation'],...catalog.profiles.map(p=>[p.profile_id,p.summary])],sources=catalog.sources.map(s=>[s.id,s.id.toUpperCase()+(s.fetch?'':' · declared inputs')]);let content;
 if(state.step===0)content=`${placeSearchMarkup()}${field('Forecast name','name',form.name)}<div class="pair">${field('Latitude °','lat',form.lat,'number','North is positive.','step="any"')}${field('Longitude °','lon',form.lon,'number','East is positive.','step="any"')}</div>${control('Region width','width',form.width,20,4000,10,'km')}${control('Region height','height',form.height,20,4000,10,'km')}<p class="help muted">The outline previews the requested area. The fitted grid is shown after configuration.</p>`;
 else if(state.step===1)content=`${select('Forcing source','source',form.source,sources,'The source registry supplies capabilities and required inputs.')}<div class="pair">${field('Cycle · UTC','cycle',form.cycle,'text','YYYY-MM-DDTHH, or latest')}${field('Forecast length · hours','hours',form.hours,'number','','min="1" step="1"')}</div>${control('Root grid spacing','dx',form.dx,.5,30,.5,'km')}<div class="pair">${field('Vertical levels','nz',form.nz,'number','Full eta controls remain in the config.','min="4" step="1"')}${field('Nest ratios','chain',form.chain,'text','Empty = one domain. Example: 3,3')}</div>${select('GPU memory mode','tiles',form.tiles,[['off','Resident grid'],['auto','Stream when needed'],['on','Force streaming']])}${field('GPU capacity · GiB (optional)','vram',form.vram,'number','Leave empty to measure this computer when building. Declare a capacity only to plan for another machine.','min="1"')}`;
 else content=`${select('Physics starting suite','profile',form.profile,profiles,'This fills the draft. After creation, each scheme and each domain can be edited independently.')}<div class="rule"></div>${field('History output interval · seconds','history',form.history,'number','Must align with the configured timesteps. The shared validator checks this.','min="1"')}<div class="field"><label>Output products</label><p class="help">Choose rendered products before launch. History data are retained by the normal engine.</p></div><div class="details"><h3>All of the controls stay available</h3><p>Radiation, microphysics, surface schemes, nesting, timesteps, streaming and restart settings remain in the complete commented TOML. Creating a draft does not launch a forecast.</p></div>`;
 return `<div class="page-title"><div><div class="eyebrow">NEW FORECAST / CONFIGURATION</div><h1>${esc(form.name)}</h1><p>Set the region, choose the run, then make it your own.</p></div><button class="quiet small" id="back-home">← Starting points</button></div><nav class="steps">${['Region','Grid & forcing','Physics & output'].map((n,i)=>`<button class="step ${state.step===i?'active':''}" data-step="${i}"><span>0${i+1}</span>${n}</button>`).join('')}</nav><section class="builder"><div class="panel"><div class="panel-title"><span>Domain footprint</span><span class="mono">GEOGRAPHIC PREVIEW</span></div><div class="map-panel">${mapMarkup(true)}</div><div class="plan-summary"><div><strong id="summary-width">${form.width} × ${form.height}</strong><small>requested km</small></div><div><strong id="summary-dx">${form.dx} km</strong><small>root resolution</small></div><div><strong>${form.hours} h</strong><small>forecast length</small></div></div><div class="map-help">Choose the area you want to forecast. You can review the exact grid before launching.</div></div><div class="panel"><div class="panel-title"><span>${['Select your region','Set the forecast','Choose a starting suite'][state.step]}</span><span class="mono">STEP ${state.step+1} / 3</span></div><div class="fields">${content}</div></div></section><div class="builder-actions"><p>All settings stay editable before launch.</p><div class="toolbar">${state.step>0?'<button class="quiet" id="prev-step">Back</button>':''}${state.step<2?'<button class="primary" id="next-step">Continue →</button>':'<button class="primary" id="create-draft">Build editable configuration →</button>'}</div></div>${jobMarkup()}`;
}
function effective(key){let raw=state.inspection.document;return raw.domain?.[state.domain]?.[key]??raw.shared?.[key]??({time_step_fract_num:0,time_step_fract_den:1}[key]??'');}
function tune(label,key,help=''){const choices=[];for(const c of Object.values(catalog.components))for(const o of Object.values(c.options||{}))if(o.selectors?.[key]!==undefined&&!choices.some(x=>x[0]===o.selectors[key]))choices.push([o.selectors[key],o.label]);const list='schemes-'+key;return field(label,'tune-'+key,effective(key),'text',help|| (choices.length?'Type an exact ID, or choose a named suggestion.':'Exact configured value.'),choices.length?`list="${list}"`:'')+(choices.length?`<datalist id="${list}">${choices.map(([id,name])=>`<option value="${id}">${esc(name)}</option>`).join('')}</datalist><span class="scheme-name">${esc(schemeName(key,effective(key)))}</span>`:'');}
function fittedRegion(){if(!state.requestedRegion)return '';const geometry=state.inspection.grid_geometry;const grids=geometry?.map(d=>`d${String(d.grid_id).padStart(2,'0')} ${d.nx} × ${d.ny} cells (${Number((d.nx*d.dx/1000).toPrecision(7))} × ${Number((d.ny*d.dy/1000).toPrecision(7))} km projected)`);return `<p class="help" id="fitted-region">Requested region: ${esc(state.requestedRegion.width_km)} × ${esc(state.requestedRegion.height_km)} km approximate. ${grids?.length?'Configured: '+esc(grids.join('; '))+'. Cell alignment, boundaries and nest clearance can add coverage.':'Configured geometry awaits a valid configuration.'}</p>`;}
function editor(){const raw=state.inspection.document,exp=raw.experiment||{},d=raw.domain?.[state.domain]||{},shared=raw.shared||{},domainChoices=(raw.domain||[]).map((d,i)=>[i,`Domain d${String(d.grid_id||i+1).padStart(2,'0')}${i===0?' · root':' · nest'}`]);let content;
 if(state.tab==='advanced')content=`<div class="panel-title"><span>Complete configuration</span><span class="mono">TOML / UTF-8</span></div><textarea class="code" id="config-text" aria-label="Complete ArWen configuration" spellcheck="false">${esc(state.draft)}</textarea><div class="code-note">Comments, unfamiliar options and per-domain settings are retained. Saving does not run anything. The engine validates scientific settings.</div>`;
 else if(state.tab==='physics')content=`<div class="panel-title"><span>Independent physics controls</span><span class="mono">EXACT SCHEME IDS</span></div><div class="fields">${select('Edit domain','edit-domain',state.domain,domainChoices,'Changes apply to the selected domain. Other domains keep their settings.')}<div class="pair">${tune('Microphysics · mp_physics','mp_physics','Scheme IDs from the engine; custom implemented choices are allowed.')}${tune('Cumulus · cu_physics','cu_physics')}</div><div class="pair">${tune('Longwave · ra_lw_physics','ra_lw_physics')}${tune('Shortwave · ra_sw_physics','ra_sw_physics')}</div>${tune('WRF radiation translation declaration','wrf_rrtmg_compatibility','A declared 4/4 translation must match the selected pair. Use none for independently selected native spectra; the value is never changed automatically.')}${select('RRTMG implementation','tune-ra_rrtmg_variant',effective('ra_rrtmg_variant'),[['rte-rrtmgp','RTE + RRTMGP'],['rrtmg_legacy','Legacy RRTMG']],'Relevant when a selected spectrum uses RRTMG.')}<div class="pair">${tune('Boundary layer · bl_pbl_physics','bl_pbl_physics')}${tune('Surface model · all domains','sf_surface_physics','This is a shared setting. Its soil layer count must match the selected surface scheme.')}</div><div class="pair">${tune('Soil layers · all domains','num_soil_layers')}${tune('Surface layer · sf_sfclay_physics','sf_sfclay_physics')}${tune('Radiation interval · minutes','radt')}</div><div class="details"><summary>Explore the shipped suites</summary><p>${catalog.profiles.map(p=>`${esc(p.summary)} <span class="mono">[MP ${p.microphysics_scheme_id}, CU ${p.cumulus_scheme_id}, PBL ${p.pbl_scheme_id}, LSM ${p.land_surface_scheme_id}, LW/SW ${p.longwave_scheme_id}/${p.shortwave_scheme_id}]</span>`).join('<br><br>')}</p></div></div>`;
 else if(state.tab==='inputs')content=`<div class="panel-title"><span>Inputs and delivery</span><span class="mono">EXISTING ENGINE DOORS</span></div><div class="fields">${field('Geography directory','geography',options.geography,'text','Native WPS geographic data used by Prepare & run.')}${field('Run output directory','output',options.output,'text','Logs and run receipts are retained alongside the normal outputs.')}${field('Rendered products','products',options.products||'','text','Empty keeps the normal defaults. Enter product IDs separated by commas, or none.')}<div class="rule"></div>${field('WPS namelist for prepared simulation','wps',options.wps||'','text','Empty uses the existing sibling config-name.namelist.wps when present. A single-domain bundle requires the exact WPS authority used during prep.')}${field('Existing prepared bundle (optional)','prepared',options.prepared||'','text','To reuse a prepared folder, select Run prepared below. Its own config/physics identity is checked.')}<div class="toolbar"><button class="quiet" id="plan-prepared">Review prepared launch</button><button class="quiet" id="run-prepared">Run prepared bundle →</button></div><div class="rule"></div><details><summary>Advanced ArWen command</summary><p class="muted">Use the existing CLI without a shell. For native prep or a WPS mapping workflow, enter a JSON array of arguments. No options are hidden.</p><textarea id="advanced-command" class="code" style="min-height:100px" aria-label="Advanced ArWen argument array">["prep", "--help"]</textarea><button id="run-advanced" class="quiet">Run this ArWen command</button></details></div>`;
 else content=`${mapMarkup()}${fittedRegion()}<div class="panel-title"><span>Forecast configuration</span><span class="mono">EDITABLE / NATIVE</span></div><div class="fields">${field('Forecast name','edit-name',exp.name)}<div class="pair">${field('Start time · UTC','edit-start',exp.start_time)}${field('Run length · seconds','edit-duration',exp.run_seconds,'number')}</div>${select('Edit domain','edit-domain',state.domain,domainChoices)}<div class="pair">${tune('Grid columns · nx','nx')}${tune('Grid rows · ny','ny')}</div><div class="pair">${state.domain===0?tune('Root grid spacing · metres','dx'):tune('Grid ratio to parent','parent_grid_ratio')}${state.domain===0?tune('Time step · whole seconds','time_step'):tune('Time step ratio to parent','parent_time_step_ratio')}</div>${state.domain===0?`<div class="pair">${tune('Fractional step · numerator','time_step_fract_num')}${tune('Fractional step · denominator','time_step_fract_den')}</div>`:''}<p class="help">Effective time step: ${esc(state.inspection.timesteps?.[state.domain]??'see validation')} seconds. Children derive their exact step from the parent ratio.</p><div class="pair">${tune('History interval · seconds','history_interval_s')}${field('Restart interval · seconds','edit-restart',exp.restart_interval_s??0,'number')}</div><p class="help muted">Geometry changes also require matching input authorities. The actual plan names any companion mismatch. Use Full config for complete nesting, eta, physics and data controls.</p></div>`;
 return `<div class="page-title"><div><div class="eyebrow">FORECAST / YOUR CONFIGURATION</div><h1>${esc(exp.name||'Forecast')}</h1><p>Review, tune, then prepare and run.</p></div><div class="toolbar"><span class="draft-badge" id="dirty-badge">${state.dirty?'UNSAVED DRAFT':'SAVED CONFIG'}</span><button class="quiet small" id="save-copy">Save a copy</button><button class="primary small" id="save-config">Save changes</button></div></div><div class="summary-grid"><div class="summary-tile"><small>Domains</small><strong>${raw.domain?.length||0}</strong></div><div class="summary-tile"><small>Root resolution</small><strong>${((raw.domain?.[0]?.dx??shared.dx??0)/1000).toLocaleString()} km</strong></div><div class="summary-tile"><small>Run length</small><strong>${((exp.run_seconds||0)>=3600?(exp.run_seconds/3600).toLocaleString()+' h':(exp.run_seconds||0).toLocaleString()+' s')}</strong></div><div class="summary-tile"><small>Vertical levels</small><strong>${shared.nz??raw.domain?.[0]?.nz??'Config'}</strong></div></div><div class="editor-layout"><section class="panel"><nav class="steps">${[['overview','Overview'],['physics','Physics'],['inputs','Inputs & output'],['advanced','Full config']].map(([id,label])=>`<button class="step ${state.tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</nav>${content}</section><aside class="panel actions-panel"><div class="panel-title"><span>Launch sequence</span><span class="mono">YOUR NEXT STEP</span></div><div class="fields"><h3>1. Review the plan</h3><p class="action-description">See the actual fetch, preparation, forecast and output commands. Nothing runs yet.</p><button class="primary" id="plan">Review launch plan <span>↗</span></button><div class="rule"></div><h3>2. Check this machine</h3><p class="action-description">Check configuration and resource readiness on this computer.</p><button class="quiet" id="check">Check readiness <span>→</span></button><div class="rule"></div><h3>3. Prepare & run</h3><p class="action-description">Acquire any needed input, prepare with native WPS, then launch the forecast.</p><button id="launch" class="quiet">Prepare & run <span>▶</span></button><p class="config-path">${esc(state.path)}</p><button class="quiet small" id="back-home">← Starting points</button></div></aside></div>${jobMarkup()}`;
}
function external(){return `<div class="external"><div class="page-title"><div><div class="eyebrow">BRING YOUR INPUTS</div><h1>Continue an existing workflow.</h1><p>Your producing namelist remains authoritative.</p></div><button class="quiet small" id="back-home">← Back</button></div><section class="panel"><div class="fields"><div class="external-choice"><button data-kind="met-em" class="${state.externalKind==='met-em'?'selected':''}"><b>WPS met_em</b><small>Native ArWen initialization from metgrid output</small></button><button data-kind="wrfinput" class="${state.externalKind==='wrfinput'?'selected':''}"><b>WRF real.exe output</b><small>wrfinput + wrfbdy, with the producing namelist</small></button></div>${field('Input directory','external-directory',state.externalDirectory||'','text',state.externalKind==='met-em'?'Contains met_em.d0*.nc and namelist.input.':'Contains wrfinput_d0*, wrfbdy_d01 and namelist.input.')}<div class="pair">${field('Run output directory','external-output',options.output)}${field('Shorten run · seconds (optional)','external-seconds',state.externalSeconds||'','number','Empty preserves the namelist duration.','min="1"')}</div><div class="toolbar"><button class="primary" id="external-plan">Inspect inputs & settings</button><button class="quiet" id="external-launch">Run with these inputs →</button></div><p class="muted">Original physics, vertical settings and input provenance stay with the producing configuration. Advanced overrides use the existing ArWen CLI.</p><div id="external-result" class="status-line">${esc(state.externalResult||'No input has been opened yet.')}</div></div></section>${jobMarkup()}</div>`;}
function render(){if(!catalog)return;$('app').innerHTML=state.view==='home'?home():state.view==='builder'?builder():state.view==='external'?external():editor();drawMap();bind();}
function collectForm(){for(const key of Object.keys(form)){let input=$(key);if(input)form[key]=input.type==='number'?(input.value===''?'':Number(input.value)):input.value;}}
function importDialog(){openDialog(`<h2>Open your ArWen configuration</h2><p>Paste the full path to a TOML file. It stays in its original folder, so relative input paths keep their meaning.</p>${field('Configuration file','import-path','','text','Example: C:\\Forecasts\\case.toml or /path/to/forecasts/case.toml')}<div class="toolbar"><button class="quiet" id="cancel-dialog">Cancel</button><button class="primary" id="open-config">Open configuration →</button></div>`);$('open-config').onclick=e=>task(e.currentTarget,async()=>{loaded(await api('open',{path:$('import-path').value}));$('dialog').close();});$('import-path').focus();}
function openDialog(html){$('dialog-content').innerHTML=html;$('dialog').showModal();if($('cancel-dialog'))$('cancel-dialog').onclick=()=>$('dialog').close();}
function loaded(result){state.path=result.path;state.draft=result.text;state.saved=result.text;state.inspection=result.inspection;state.requestedRegion=result.requested_region||null;state.dirty=false;state.domain=0;state.view='editor';state.tab='overview';render();fitRegion();}
function markDirty(){state.dirty=state.draft!==state.saved;if($('dirty-badge'))$('dirty-badge').textContent=state.dirty?'UNSAVED DRAFT':'SAVED CONFIG';}
async function patch(changes){let result=await api('patch',{text:state.draft,changes});state.draft=result.text;state.inspection=result.inspection;markDirty();drawMap();if($('fitted-region'))$('fitted-region').outerHTML=fittedRegion();if(result.inspection.validation_error)notice(result.inspection.validation_error);}
async function save(){if($('config-text'))state.draft=$('config-text').value;let result=await api('save',{text:state.draft});state.saved=state.draft;markDirty();state.inspection=await api('inspect',{text:state.draft});notice('Saved. Previous bytes retained in '+result.backup,true);}
function start(mode,extra={}){return task(null,async()=>{if(mode==='plan')state.planSnapshot={document:structuredClone(state.inspection.document),output:options.output};state.job=await api('start',{mode,text:state.draft,output:options.output,geography:options.geography,products:options.products,...extra});render();$('job')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});poll();});}
function launchDialog(mode='run',extra={}){openDialog(`<h2>${mode==='external-run'?'Run with your existing inputs?':'Prepare and launch this forecast?'}</h2><p>${mode==='external-run'?'The existing producing configuration will be used.':'ArWen will execute the saved configuration. Required forcing may be downloaded, then native preparation and the forecast will run.'} Logs and outputs are retained locally.</p><p class="mono">${esc(mode==='external-run'?extra.directory:state.path)}</p><div class="toolbar"><button class="quiet" id="cancel-dialog">Keep editing</button><button class="primary" id="confirm-launch">${mode==='external-run'?'Run forecast':'Prepare & run'} ▶</button></div>`);$('confirm-launch').onclick=()=>{$('dialog').close();start(mode,extra);};}
async function poll(){clearTimeout(timer);try{state.job=await api('status');const job=$('job');if(job){let holder=document.createElement('div');holder.innerHTML=jobMarkup();const wasOpen=job.querySelector('details')?.open;let oldLog=$('job-log'),atBottom=oldLog?(oldLog.scrollHeight-oldLog.scrollTop-oldLog.clientHeight<50):true;job.replaceWith(holder.firstElementChild);if(wasOpen&&$('job')?.querySelector('details'))$('job').querySelector('details').open=true;if(atBottom&&$('job-log'))$('job-log').scrollTop=$('job-log').scrollHeight;bindJob();}else render();$('footer-status').textContent=state.job.active?'Command active · output retained locally':'Local engine · your machine, your files';if(state.job.active)timer=setTimeout(poll,900);}catch(e){notice(e.message);}}
function bindJob(){if($('open-results'))$('open-results').onclick=e=>task(e.currentTarget,()=>api('open-results'));if($('stop'))$('stop').onclick=()=>{openDialog(`<h2>Stop this command?</h2><p>This stops only the process tree started by this launchpad. Partial output and any existing checkpoints stay on disk. Stopping does not create a checkpoint.</p><div class="toolbar"><button class="quiet" id="cancel-dialog">Keep running</button><button class="danger" id="confirm-stop">Stop this command</button></div>`);$('confirm-stop').onclick=()=>task(null,async()=>{$('dialog').close();state.job=await api('stop');poll();});};}
function bind(){bindJob();bindMap();bindPlaceSearch();if($('back-home'))$('back-home').onclick=goHome;if($('import-config'))$('import-config').onclick=importDialog;if($('external-inputs'))$('external-inputs').onclick=()=>{state.view='external';render();};if($('return-draft'))$('return-draft').onclick=()=>{state.view='editor';render();};
 document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{Object.assign(form,starters.find(p=>p.id===b.dataset.preset).values);state.step=0;state.view='builder';render();fitRegion();});
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{collectForm();state.step=Number(b.dataset.step);render();});
 if($('prev-step'))$('prev-step').onclick=()=>{collectForm();state.step--;render();};if($('next-step'))$('next-step').onclick=()=>{collectForm();state.step++;render();};
 ['lat','lon'].forEach(k=>{if($(k))$(k).oninput=()=>{form[k]=Number($(k).value);clearPlaceSelection();drawMap();};});
 ['width','height','dx'].forEach(k=>bindControl(k,v=>{form[k]=v;drawMap();if($('summary-width'))$('summary-width').textContent=`${form.width} × ${form.height}`;if($('summary-dx'))$('summary-dx').textContent=form.dx+' km';}));
 if($('create-draft'))$('create-draft').onclick=e=>{collectForm();task(e.currentTarget,async()=>{loaded(await api('create',form));notice('Configuration ready. Review the plan before starting a forecast.',true);});};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>task(null,async()=>{if($('config-text')){state.draft=$('config-text').value;markDirty();state.inspection=await api('inspect',{text:state.draft});}state.tab=b.dataset.tab;render();}));
 if($('config-text'))$('config-text').oninput=()=>{state.draft=$('config-text').value;markDirty();};
 if($('save-config'))$('save-config').onclick=e=>task(e.currentTarget,save);
 if($('save-copy'))$('save-copy').onclick=()=>{openDialog(`<h2>Save a new copy</h2><p>The original is retained. Relative input paths resolve from the new folder; keep the copy beside the original to retain that meaning.</p>${field('Full path for the new TOML','copy-path',state.path.replace(/\.toml$/,'.copy.toml'))}<div class="toolbar"><button class="quiet" id="cancel-dialog">Cancel</button><button class="primary" id="write-copy">Save new copy</button></div>`);$('write-copy').onclick=e=>task(e.currentTarget,async()=>{const r=await api('save-as',{path:$('copy-path').value,text:state.draft});$('dialog').close();notice(r.message,true);});};
 if($('edit-domain'))$('edit-domain').onchange=()=>{state.domain=Number($('edit-domain').value);render();};
 document.querySelectorAll('[id^="tune-"]').forEach(input=>input.onchange=()=>task(null,async()=>{const key=input.id.slice(5),value=input.tagName==='SELECT'?input.value:(input.value.trim()!==''&&!Number.isNaN(Number(input.value))?Number(input.value):input.value);await patch([{path:catalog.domain_keys.includes(key)?`domain/${state.domain}/${key}`:`shared/${key}`,value}]);}));
 [['edit-name','name'],['edit-start','start_time'],['edit-duration','run_seconds'],['edit-restart','restart_interval_s']].forEach(([id,key])=>{if($(id))$(id).onchange=()=>task(null,()=>patch([{path:`experiment/${key}`,value:$(id).type==='number'?Number($(id).value):$(id).value}]))});
 ['geography','output','products','prepared','wps'].forEach(id=>{if($(id))$(id).onchange=()=>options[id]=$(id).value;});
 if($('plan'))$('plan').onclick=()=>start('plan');if($('check'))$('check').onclick=()=>start('check');if($('launch'))$('launch').onclick=()=>launchDialog();if($('run-prepared'))$('run-prepared').onclick=()=>launchDialog('prepared',{prepared:options.prepared,wps:options.wps});if($('plan-prepared'))$('plan-prepared').onclick=()=>start('prepared-plan',{prepared:options.prepared,wps:options.wps});
 if($('run-advanced'))$('run-advanced').onclick=()=>{try{const argv=JSON.parse($('advanced-command').value);openDialog(`<h2>Run this ArWen command?</h2><p class="mono">${esc(JSON.stringify(argv))}</p><p>The existing engine receives these exact arguments. No shell is used.</p><div class="toolbar"><button class="quiet" id="cancel-dialog">Cancel</button><button class="primary" id="confirm-advanced">Run command</button></div>`);$('confirm-advanced').onclick=()=>{$('dialog').close();start('advanced',{argv});};}catch(e){notice(e.message);}};
 document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{state.externalDirectory=$('external-directory').value;state.externalKind=b.dataset.kind;render();});
 if($('external-directory'))$('external-directory').onchange=()=>state.externalDirectory=$('external-directory').value;
 if($('external-output'))$('external-output').onchange=()=>options.output=$('external-output').value;
 if($('external-seconds'))$('external-seconds').onchange=()=>state.externalSeconds=$('external-seconds').value;
 if($('external-plan'))$('external-plan').onclick=e=>task(e.currentTarget,async()=>{const r=await api('external-plan',{kind:state.externalKind,directory:$('external-directory').value});state.externalResult=`${r.name} · ${r.domains} domains · ${r.seconds} seconds from ${r.start}. ${r.message}`;$('external-result').textContent=state.externalResult;});
 if($('external-launch'))$('external-launch').onclick=()=>launchDialog('external-run',{kind:state.externalKind,directory:$('external-directory').value,...(state.externalSeconds?{run_seconds:Number(state.externalSeconds)}:{})});
}
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='Your draft has unsaved changes.';}});
(async()=>{try{options=await api('catalog');catalog=options.catalog;options.output=options.workspace+'/runs';form.source=catalog.default_source;form.cycle=catalog.cycle;render();poll();loadGeography();}catch(e){$('app').innerHTML=`<div class="empty"><div class="eyebrow">LOCAL ENGINE SETUP</div><h1>Let’s connect ArWen.</h1><p>${esc(e.message)}</p><p style="margin-top:20px">Start the launchpad with the Python environment where ArWen is installed. No forecast has started.</p><button class="primary" style="margin-top:20px" onclick="location.reload()">Retry connection</button></div>`;}})();
