"""The air-gapped Rust build, proved as a property rather than a habit.

The reopening battery could not build the tree's own HRRR decoder offline
and read the failure -- ``no matching package named 'chrono' found`` -- as a
gap in the vendored registry.  It is not: ``chrono 0.4.45`` has been vendored
and tracked since the baseline commit, and ``cargo build --release --locked
--offline`` succeeds *from inside* ``tools/grib1_bridge``.

The real defect is one directory up.  Cargo discovers ``.cargo/config.toml``
-- which is where the crates.io -> ``vendor/crates-io`` source replacement
lives -- by walking UP from the **working directory**, never from
``--manifest-path``.  So a build driven from the repository root silently
bypasses the vendored registry and resolves against crates.io, which on an
air-gapped box fails naming whichever crate the resolver reached first.  That
is exactly what ``tools/prepare_hrrr_wrf.py``'s decoder auto-build,
``tools/prepare_hrrr_500_native.sh`` and ``docs/benchmark.md`` used to do,
while README/install.sh/install.ps1/CONTRIBUTING all ``cd`` into the crate --
which is why every other Rust target built cleanly and this one did not.

Two properties are bound here, because the wrong diagnosis was still a real
report and both halves have to stay true: the vendored registry is complete
for every locked dependency, and no shipped build path builds a vendored
workspace from outside it.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[1]

#: Every vendored cargo workspace in the tree, in VENDOR.md's terms: a
#: ``Cargo.lock``, a ``.cargo/config.toml`` source replacement, and a
#: ``vendor/crates-io`` directory generated by ``cargo vendor``.
_WORKSPACES = ("tools/grib1_bridge", "tools/rustwx")

_PACKAGE_NAME = re.compile(r'^name = "(?P<name>[^"]+)"', re.M)
_PACKAGE_SOURCE = re.compile(r'^source = "(?P<source>[^"]+)"', re.M)


def _locked_external_packages(workspace: Path) -> list[str]:
    """Package names in ``Cargo.lock`` that come from outside the tree.

    A package with no ``source`` is a path member of the workspace itself
    and is not vendored; everything else -- crates.io and git alike -- is
    what ``cargo vendor`` writes into ``vendor/crates-io``.
    """

    text = (workspace / "Cargo.lock").read_text(encoding="utf-8")
    names = []
    for block in text.split("[[package]]")[1:]:
        name = _PACKAGE_NAME.search(block)
        source = _PACKAGE_SOURCE.search(block)
        if name and source:
            names.append(name.group("name"))
    return names


@pytest.mark.parametrize("relative", _WORKSPACES)
def test_every_locked_dependency_is_vendored(relative: str) -> None:
    workspace = _ROOT / relative
    replacement = (workspace / ".cargo" / "config.toml").read_text(
        encoding="utf-8")
    assert 'replace-with = "vendored-sources"' in replacement
    assert 'directory = "vendor/crates-io"' in replacement

    registry = workspace / "vendor" / "crates-io"
    locked = _locked_external_packages(workspace)
    assert locked, f"{relative} locks no external dependency"
    missing = [
        name for name in locked
        if not (registry / name / ".cargo-checksum.json").is_file()
        or not (registry / name / "Cargo.toml").is_file()
    ]
    assert not missing, (
        f"{relative}/vendor/crates-io is missing {sorted(missing)}; "
        "regenerate it with `cargo vendor --locked vendor/crates-io` and "
        "record the change in VENDOR.md")


def test_the_vendored_registry_check_can_fail(tmp_path: Path) -> None:
    """The control: a lock naming an unvendored crate must be caught."""

    workspace = tmp_path / "crate"
    (workspace / "vendor" / "crates-io" / "present").mkdir(parents=True)
    for name in (".cargo-checksum.json", "Cargo.toml"):
        (workspace / "vendor" / "crates-io" / "present" / name).write_text(
            "{}", encoding="utf-8")
    (workspace / "Cargo.lock").write_text(
        '[[package]]\nname = "present"\nsource = "registry+x"\n\n'
        '[[package]]\nname = "absent"\nsource = "registry+x"\n',
        encoding="utf-8")

    locked = _locked_external_packages(workspace)
    assert locked == ["present", "absent"]
    registry = workspace / "vendor" / "crates-io"
    assert not (registry / "absent" / ".cargo-checksum.json").is_file()


#: Files that tell a user or a script how to build a vendored workspace.
#: Handoff reports are excluded: they record what was run, not what to run.
_BUILD_SITES = (
    "tools/prepare_hrrr_wrf.py",
    "tools/prepare_hrrr_500_native.sh",
    "tools/prepare_hrrr_native.sh",
    "docs/benchmark.md",
    "docs/install.md",
    "docs/public/FIRST-LIGHT.md",
    "README.md",
    "CONTRIBUTING.md",
    "install.sh",
    "install.ps1",
)


def test_no_shipped_build_path_bypasses_the_vendored_registry() -> None:
    """``--manifest-path`` into a vendored workspace defeats ``--offline``.

    The build must be driven from inside the crate, because that is the
    only place cargo looks for the source replacement.
    """

    offenders = []
    for relative in _BUILD_SITES:
        path = _ROOT / relative
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for workspace in _WORKSPACES:
            crate = workspace.rsplit("/", 1)[-1]
            for line_number, line in enumerate(text.splitlines(), 1):
                if line.lstrip().startswith("#"):
                    continue
                if "manifest-path" in line and crate in line:
                    offenders.append(f"{relative}:{line_number}")
    assert not offenders, (
        "these build sites reach a vendored cargo workspace through "
        f"--manifest-path and cannot build air-gapped: {offenders}; use "
        "`cd <crate> && cargo build --release --locked --offline`")
