"""Every non-Python file under ``gpuwm/`` must be declared as package data.

The whole suite reads its oracle fixtures and parameter tables out of the
source tree, so a file that is missing from ``[tool.setuptools.package-data]``
still passes every test while the built wheel silently omits it.  That is not a
hypothetical: before this gate existed the declaration was a hand-maintained
enumeration that had fallen 52 files behind, including three assets the model
loads at *runtime* rather than only under test --
``data/kf_lutab/kf_lutab.npz`` (``gpuwm.core.kf``), ``data/noahmp/*.TBL``
(``gpuwm.core.noahmp``) and ``data/ruc/oracle/tbq.csv``
(``gpuwm.core.ruc._load_ruc_saturation_table``).  An install of that wheel
raises ``FileNotFoundError`` the first time those schemes are used.

The check runs setuptools' own :meth:`build_py.find_data_files` against the
real ``pyproject.toml`` rather than re-implementing pattern matching, so what
it reports is what the wheel would actually contain.  It is a filesystem walk,
not a ``git ls-files`` walk, so an undeclared file trips it before it is ever
committed.

Why the walk stops at ``gpuwm/``
-------------------------------
``tools`` is a declared package too, but it is not a data directory: it is
mostly scripts, plus two vendored Rust workspaces whose source is *build
input* and has no business in a wheel.  A blanket "everything under ``tools``
must ship" rule would be wrong in 260 MB of ways.

That exemption is exactly how the renderer's map assets disappeared.
``tools/rustwx/assets/basemap`` holds the Natural Earth and US Census
shapefiles ``rw_wrfbatch`` draws coastlines and borders from -- runtime data
living inside a directory this file had decided not to look at -- and the one
``package-data`` entry still written as an enumeration, ``tools =
["prepare_hrrr_*.sh"]``, did not name them.  Nothing failed.  A pip install
rendered a tropical cyclone over a blank rectangle.

So the rule is not "walk more", it is "every *runtime* asset must be
delivered by some declared mechanism, and the test names which".  For the
renderer's assets that mechanism is the bridge bundle rather than the wheel
(the wheel is 74.6 MiB against PyPI's 100 MB per-file cap and the assets
deflate to 20.2 MiB), which
:func:`test_the_renderer_asset_tree_is_delivered_by_a_declared_mechanism`
checks against ``gpuwm.bridge_assets``.
"""

from __future__ import annotations

import glob as globlib
import os
import tomllib
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = REPO_ROOT / "pyproject.toml"
PACKAGE_ROOT = REPO_ROOT / "gpuwm"

#: Extensions that ``[tool.setuptools.packages.find]`` already ships as modules,
#: plus their compiled droppings.  Everything else under ``gpuwm/`` is data.
_MODULE_SUFFIXES = (".py", ".pyc", ".pyo")

#: Directories that never belong in a distribution at all.
_SKIP_DIRS = frozenset({"__pycache__", ".pytest_cache", ".ruff_cache"})


def _require_source_tree() -> None:
    if not PYPROJECT.is_file() or not PACKAGE_ROOT.is_dir():
        pytest.skip("packaging gate needs the source tree, not an install")


#: The ONLY files that may be deliberately absent from the wheel, in two
#: pinned classes.  Anything else excluded from the wheel is a packaging
#: bug, and either list going stale is one too.
#:
#: License-driven: the four CC-BY-NC-SA-4.0 RFMIP reference-result NetCDFs
#: (gpuwm/data/rrtmgp/PROVENANCE.md) -- in-repo test fixtures whose
#: non-commercial license must not attach to the distributable.  These
#: must stay in the repo.
_LICENSE_EXCLUDED_FROM_WHEEL = frozenset({
    "gpuwm/data/rrtmgp/rfmip-clear-sky-reference-lw-down.nc",
    "gpuwm/data/rrtmgp/rfmip-clear-sky-reference-lw-up.nc",
    "gpuwm/data/rrtmgp/rfmip-clear-sky-reference-sw-down.nc",
    "gpuwm/data/rrtmgp/rfmip-clear-sky-reference-sw-up.nc",
})

#: Size-driven externalized assets: published as GitHub release assets
#: because they exceed distribution-channel limits, staged by
#: ``gpuwm fetch-tables`` under the thompson_contract size+SHA-256 pins.
#: Unlike the license class these MAY be absent from a checkout
#: (freezeH2O.dat is not in the public repository at all); when present
#: they still must not ship in the wheel or the sdist.  Pinned against
#: gpuwm.table_assets and MANIFEST.in so the packaging exclusions and
#: the fetch contract cannot drift apart.
_EXTERNALIZED_FROM_WHEEL = frozenset({
    "gpuwm/data/thompson/tables/freezeH2O.dat",
    "gpuwm/data/thompson/tables/qr_acr_qg_V4.dat",
})

#: Third-party data this repository redistributes verbatim from a WRF
#: release, which therefore must SHIP rather than be excluded.
#:
#: ``CCN_ACTIVATE.BIN`` is the aerosol-aware Thompson (mp_physics=28)
#: activation table.  It is not generated by ``thompson_init`` and no
#: recompilation of WRF reproduces it -- ``table_ccnAct``
#: (phys/module_mp_thompson.F:5110-5166) only READS it, and the numbers are
#: offline parcel-model output (WRF's own comment at :5102-5108).  Until
#: 2026-08-01 the port did not redistribute it and ``pyproject.toml`` carried
#: an explicit ``exclude-package-data`` entry to keep a wheel built on a
#: machine that had staged it from publishing it.  That decision was
#: reversed: the committed copy is WRF v4.6.1's ``run/CCN_ACTIVATE.BIN`` bit
#: for bit, WRF's ``LICENSE.txt`` is a public-domain dedication, and the
#: notice ships in ``gpuwm/data/wrf_radiation/LICENSE-WRF.txt``.  The pin
#: below is therefore inverted: these files must reach the wheel, and the
#: exclusion entry must be gone.  See ``gpuwm/data/thompson/PROVENANCE.md``
#: and ``thompson_aerosol_contract.AEROSOL_ASSET_REDISTRIBUTED``.
_REDISTRIBUTED_WRF_DATA = frozenset({
    "gpuwm/data/thompson/tables/CCN_ACTIVATE.BIN",
})


def _build_system_requires() -> list[str]:
    """What this project declares it needs in order to be built at all."""

    with PYPROJECT.open("rb") as stream:
        config = tomllib.load(stream)
    return list(config.get("build-system", {}).get("requires", []))


def _package_data_declaration() -> dict[str, list[str]]:
    with PYPROJECT.open("rb") as stream:
        config = tomllib.load(stream)
    return config["tool"]["setuptools"]["package-data"]


def _exclude_package_data_declaration() -> dict[str, list[str]]:
    with PYPROJECT.open("rb") as stream:
        config = tomllib.load(stream)
    return config["tool"]["setuptools"].get("exclude-package-data", {})


def _discover_packages() -> list[str]:
    """Import names of every package under ``gpuwm/`` (an ``__init__.py`` dir)."""

    packages: list[str] = []
    for dirpath, dirnames, filenames in os.walk(PACKAGE_ROOT):
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        if "__init__.py" not in filenames:
            continue
        relative = Path(dirpath).relative_to(REPO_ROOT)
        packages.append(".".join(relative.parts))
    return packages


def _files_on_disk() -> set[str]:
    """Repo-relative POSIX paths of every data file physically under ``gpuwm/``."""

    present: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(PACKAGE_ROOT):
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        for name in filenames:
            if name.endswith(_MODULE_SUFFIXES):
                continue
            path = Path(dirpath, name).relative_to(REPO_ROOT)
            present.add(path.as_posix())
    return present


def _files_setuptools_would_ship(monkeypatch: pytest.MonkeyPatch) -> set[str]:
    """Ask setuptools itself which files the declaration selects.

    ``build_py.get_data_files_without_manifest`` is the exact code path that
    populates a wheel, so this measures the declaration rather than trusting a
    private re-implementation of glob semantics.

    An absent setuptools is a FAILURE here, not a skip.  It used to be
    ``pytest.importorskip("setuptools")``, and the 2026-08-13 test-estate
    audit measured the consequence: this file is on
    ``tools/battery/stage1_files.txt`` and was **56% dark** on the assembly
    venvs -- 4 passed, 5 skipped -- and the five that skipped are exactly
    the wheel-content assertions the file exists for (every data file
    declared, the exclusion lists, the renderer asset tree, the runtime
    assets, the Thompson table).  That is the same class as the defect
    ``fix(render): the map assets ship with the renderer that reads them``
    closed, and a stage-1 entry cannot be allowed to report green while its
    reason for existing is switched off.

    A skip would be defensible if setuptools were optional.  It is not:
    ``[build-system] requires`` in this project's own pyproject.toml names
    ``setuptools>=77``, so any environment that can build this project has
    it, and one that does not cannot answer the question this file asks.
    The remedy is one line -- ``pip install setuptools`` -- and the message
    below says so.
    """

    try:
        import setuptools
    except ModuleNotFoundError as exc:      # pragma: no cover - env defect
        requires = _build_system_requires()
        assert any(r.replace("_", "-").lower().startswith("setuptools")
                   for r in requires), (
            "setuptools is absent AND [build-system] requires no longer names "
            f"it ({requires}); this file's premise has changed, so decide "
            "deliberately whether the wheel-content assertions still apply")
        raise AssertionError(
            "setuptools is not installed, so the five wheel-content "
            "assertions in this file cannot run -- and this file is on "
            "tools/battery/stage1_files.txt, where a silent skip reports "
            f"green.  pyproject.toml's [build-system] requires {requires}, so "
            "every environment that can build this project has it.  Remedy: "
            "pip install setuptools (or install the project with "
            "'pip install -e .[dev,render]' in a venv built with it)."
        ) from exc

    from setuptools.command.build_py import build_py

    packages = _discover_packages()
    assert "gpuwm" in packages, f"package discovery is broken: {packages}"

    distribution = setuptools.dist.Distribution({
        "name": "gpuwm",
        "packages": packages,
        "package_data": _package_data_declaration(),
        "exclude_package_data": _exclude_package_data_declaration(),
    })
    command = build_py(distribution)
    command.finalize_options()

    # setuptools globs relative to the working directory.
    monkeypatch.chdir(REPO_ROOT)

    shipped: set[str] = set()
    for _package, src_dir, _build_dir, filenames in (
        command.get_data_files_without_manifest()
    ):
        for name in filenames:
            shipped.add(Path(src_dir, name).as_posix())
    return shipped


def test_the_wheel_content_assertions_cannot_go_dark_by_skipping() -> None:
    """The premise behind refusing to skip on an absent setuptools.

    The 2026-08-13 test-estate audit measured this file at 4 passed / 5
    skipped on the assembly venvs, and the five that skipped are the whole
    point of the file.  ``_files_setuptools_would_ship`` now raises instead,
    which is only defensible while setuptools really is a build requirement
    of this project rather than an optional extra.  This is that check: if
    the build backend ever moves, the assertion below fails and whoever
    moves it has to decide what these five assertions become, instead of
    silently inheriting a skip.
    """

    requires = _build_system_requires()
    assert requires, "pyproject.toml declares no [build-system] requires"
    assert any(r.replace("_", "-").lower().startswith("setuptools")
               for r in requires), (
        f"[build-system] requires is {requires} and no longer names "
        "setuptools, so 'every environment that can build this project has "
        "setuptools' has stopped being true.  _files_setuptools_would_ship "
        "raises on an absent setuptools on the strength of that sentence")


def test_every_data_file_under_gpuwm_is_declared(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """No data file may reach ``gpuwm/`` without ``package-data`` covering it."""

    _require_source_tree()
    present = _files_on_disk()
    assert present, "found no data files under gpuwm/ -- the walk is broken"

    shipped = _files_setuptools_would_ship(monkeypatch)
    undeclared = sorted(present - shipped - _LICENSE_EXCLUDED_FROM_WHEEL
                        - _EXTERNALIZED_FROM_WHEEL)
    assert not undeclared, (
        f"{len(undeclared)} data file(s) under gpuwm/ would be omitted from a "
        "wheel because [tool.setuptools.package-data] in pyproject.toml does "
        "not cover them. Widen an existing glob (do not append a filename):\n  "
        + "\n  ".join(undeclared)
    )


def test_wheel_exclusions_are_exactly_the_pinned_lists(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Only the license fixtures and the size-externalized assets.

    Both directions matter: an exclusion pattern that silently widened
    would strip runtime data from the wheel, and a named fixture leaving
    the repo would break the RFMIP acceptance gates that read it.  The
    externalized assets may legitimately be absent from a checkout (the
    public repository ships them as release assets); when present they
    still must not reach the wheel.

    There is no third, redistribution-driven class any more.
    ``CCN_ACTIVATE.BIN`` was the only member and it ships now, so it must
    appear on the OTHER side of this comparison -- a re-added exclusion for
    it fails here as an unexpected exclusion.
    """

    _require_source_tree()
    present = _files_on_disk()
    shipped = _files_setuptools_would_ship(monkeypatch)
    excluded = present - shipped
    expected = set(_LICENSE_EXCLUDED_FROM_WHEEL) | (
        set(_EXTERNALIZED_FROM_WHEEL) & present)
    assert excluded == expected, (
        "wheel exclusions drifted from the pinned lists:\n"
        f"  unexpectedly excluded: {sorted(excluded - expected)}\n"
        f"  expected but shipped/missing: {sorted(expected - excluded)}"
    )
    for relative in sorted(_LICENSE_EXCLUDED_FROM_WHEEL):
        assert (REPO_ROOT / relative).is_file(), (
            f"license-excluded test fixture vanished from the repo: {relative}"
        )
    # The applicable license text still ships beside the surviving rrtmgp
    # data so PROVENANCE.md stays resolvable inside an installed wheel.
    assert "gpuwm/data/rrtmgp/LICENSE-CC-BY-NC-SA-4.0" in shipped


def test_externalized_assets_match_the_fetch_contract() -> None:
    """The packaging pin and gpuwm.table_assets must name the same files,
    and every one must carry a size+SHA-256 pin in thompson_contract."""

    from gpuwm.core.thompson_contract import CLASSIC_TABLE_ASSETS
    from gpuwm.table_assets import EXTERNALIZED_TABLE_FILENAMES

    pinned_names = {Path(p).name for p in _EXTERNALIZED_FROM_WHEEL}
    assert pinned_names == set(EXTERNALIZED_TABLE_FILENAMES)
    contract_names = {asset.filename for asset in CLASSIC_TABLE_ASSETS}
    assert set(EXTERNALIZED_TABLE_FILENAMES) <= contract_names
    # MANIFEST.in must exclude exactly the same files from the sdist
    # (exclude-package-data governs the wheel only).
    manifest = (REPO_ROOT / "MANIFEST.in").read_text(encoding="utf-8")
    manifest_excludes = {
        line.split(None, 1)[1].strip()
        for line in manifest.splitlines()
        if line.startswith("exclude ")
    }
    assert manifest_excludes == set(_EXTERNALIZED_FROM_WHEEL)


def test_the_renderer_asset_tree_is_delivered_by_a_declared_mechanism(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """No runtime asset under ``tools/`` may be delivered by nothing at all.

    The gap this closes: the wheel-coverage walk above deliberately stops at
    ``gpuwm/``, so a data directory under ``tools/`` could -- and did -- reach
    an installed user by no mechanism whatever, silently, and the only symptom
    was a plot with no geography on it.

    Every file under the renderer's asset root must therefore be accounted
    for by one of the two mechanisms that exist: the wheel's package-data, or
    the bridge bundle.  A new asset subdirectory that nobody added to
    ``bridge_assets.REQUIRED_ASSET_SUBDIRS`` is delivered by neither, and
    fails here by name rather than months later in an image.
    """

    _require_source_tree()
    from gpuwm import bridge_assets

    asset_root = REPO_ROOT / "tools" / "rustwx" / "assets"
    if not asset_root.is_dir():
        pytest.skip("no vendored renderer assets in this tree")

    present: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(asset_root):
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        for name in filenames:
            present.add(
                Path(dirpath, name).relative_to(REPO_ROOT).as_posix())
    assert present, "found no renderer assets -- the walk is broken"

    carried_by_bundle = {
        path for path in present
        if Path(path).relative_to(
            asset_root.relative_to(REPO_ROOT)).parts[0]
        in bridge_assets.REQUIRED_ASSET_SUBDIRS
    }
    shipped_in_wheel = _files_setuptools_would_ship(monkeypatch)
    undelivered = sorted(present - carried_by_bundle - shipped_in_wheel)
    assert not undelivered, (
        f"{len(undelivered)} renderer asset file(s) would reach an installed "
        "user by no mechanism at all -- not the wheel's "
        "[tool.setuptools.package-data], and not the bridge bundle's "
        "gpuwm.bridge_assets.REQUIRED_ASSET_SUBDIRS. A renderer without them "
        "draws plots with no coastlines or borders:\n  "
        + "\n  ".join(undelivered))

    # The declaration must also still name something real: a subdirectory
    # renamed on disk leaves REQUIRED_ASSET_SUBDIRS pointing at nothing, and
    # the bundle would be packed empty.
    for subdir in bridge_assets.REQUIRED_ASSET_SUBDIRS:
        candidate = asset_root / subdir
        assert candidate.is_dir(), (
            f"bridge_assets.REQUIRED_ASSET_SUBDIRS names {subdir!r}, which is "
            f"not a directory at {candidate}")
        assert any(p.is_file() for p in candidate.rglob("*")), (
            f"{candidate} holds no files; the bundle would carry no basemaps")


def test_no_package_data_pattern_is_dead(monkeypatch: pytest.MonkeyPatch) -> None:
    """A pattern that matches nothing is drift -- it names a moved directory."""

    _require_source_tree()
    monkeypatch.chdir(REPO_ROOT)

    declaration = _package_data_declaration()
    dead: list[str] = []
    for package, patterns in declaration.items():
        package_dir = REPO_ROOT.joinpath(*package.split("."))
        for pattern in patterns:
            if not package_dir.is_dir():
                dead.append(f"{package}: <no such package dir> ({pattern})")
                continue
            matches = globlib.glob(
                pattern, root_dir=package_dir, recursive=True
            )
            if not any((package_dir / m).is_file() for m in matches):
                dead.append(f"{package}: {pattern}")

    assert not dead, (
        "package-data pattern(s) match no file on disk; the data they named has "
        "moved or been deleted:\n  " + "\n  ".join(dead)
    )


def test_runtime_data_assets_survive_the_globs(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Pin the assets whose absence breaks an *installed* model, not just tests.

    The coverage test above is only as strong as the filesystem it walks. These
    three are loaded by physics code at run time, so an installed wheel without
    them is broken in the field rather than in CI -- worth failing loudly and by
    name if a future rewrite of the globs drops them.
    """

    _require_source_tree()
    shipped = _files_setuptools_would_ship(monkeypatch)
    for relative in (
        "gpuwm/data/kf_lutab/kf_lutab.npz",
        "gpuwm/data/morrison/constants.toml",
        "gpuwm/data/thompson/tables/qr_acr_qsV2.dat",
        "gpuwm/data/thompson/tables/thompson_aux_tables.dat",
        "gpuwm/data/thompson/tables/MANIFEST.sha256",
        "gpuwm/data/noahmp/MPTABLE.TBL",
        "gpuwm/data/noahmp/SOILPARM.TBL",
        "gpuwm/data/noahmp/GENPARM.TBL",
        "gpuwm/data/noah_tables/VEGPARM.TBL",
        "gpuwm/data/ruc/oracle/tbq.csv",
        "gpuwm/data/rrtmgp/rrtmgp-gas-lw-g256.nc",
        "gpuwm/data/wrf_radiation/RRTM_DATA",
    ):
        assert (REPO_ROOT / relative).is_file(), f"fixture vanished: {relative}"
        assert relative in shipped, (
            f"{relative} is loaded at run time but would not ship in a wheel"
        )
    # The externalized tables are loaded at run time too, but deliberately
    # NOT via the wheel: they are release assets staged by
    # `gpuwm fetch-tables`, so the pin here is inverted -- they must never
    # ship even when present in the tree.
    for relative in sorted(_EXTERNALIZED_FROM_WHEEL):
        assert relative not in shipped, (
            f"{relative} is externalized and must not ship in the wheel"
        )


def test_the_thompson_aerosol_table_reaches_the_wheel(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """gpuwm declares it ships this file, so the wheel must actually have it.

    ``CCN_ACTIVATE.BIN`` is the one Thompson coefficient artifact that is not
    a ``thompson_init`` product: it is third-party parcel-model output WRF
    redistributes, and until 2026-08-01 this repository did not.  The pin has
    been inverted rather than deleted, because it is the same failure in the
    other direction: an ``exclude-package-data`` entry left behind, or the
    ``.gitignore`` line reinstated, would ship an mp=28 that fails closed on a
    missing asset for every user while the constant still claimed otherwise.

    The pin is bound to ``AEROSOL_ASSET_REDISTRIBUTED`` so the decision moves
    in one place: flip that constant back and this test tells you the
    packaging entry has to move with it.
    """

    _require_source_tree()
    from gpuwm.core.thompson_aerosol_contract import (
        AEROSOL_ASSET_REDISTRIBUTED,
        AEROSOL_TABLE_ASSETS,
    )

    assert AEROSOL_ASSET_REDISTRIBUTED is True, (
        "the port declares this asset redistributed; if that changed, the "
        "wheel exclusion and gpuwm/data/thompson/PROVENANCE.md change with it")
    pinned = {asset.filename for asset in AEROSOL_TABLE_ASSETS}
    assert {Path(p).name for p in _REDISTRIBUTED_WRF_DATA} == pinned

    shipped = _files_setuptools_would_ship(monkeypatch)
    withheld = sorted(_REDISTRIBUTED_WRF_DATA - shipped)
    assert withheld == [], (
        "these files are declared redistributed by gpuwm yet the wheel would "
        f"not contain them: {withheld}\n"
        "Remove the matching [tool.setuptools.exclude-package-data] entry in "
        "pyproject.toml under the 'gpuwm' key, or widen "
        "[tool.setuptools.package-data]."
    )

    # ...and the shipped bytes must be the pinned WRF v4.6.1 file, not some
    # other 35 KB table: shipping the wrong one is worse than shipping none.
    for relative in sorted(_REDISTRIBUTED_WRF_DATA):
        path = REPO_ROOT / relative
        assert path.is_file(), (
            f"{relative} is declared redistributed but is not in the tree")
        assert path.stat().st_size == next(
            asset.bytes for asset in AEROSOL_TABLE_ASSETS
            if asset.filename == path.name), (
            f"{relative} is present but is not the pinned WRF v4.6.1 file")


def test_the_redistributed_table_is_not_excluded_in_the_pyproject_declaration(
) -> None:
    """The same pin, asserted without setuptools, so it actually runs.

    Every other test in this module routes through
    :func:`_files_setuptools_would_ship`, which begins with
    ``pytest.importorskip("setuptools")``.  That is the right call for a
    measurement of real wheel contents -- a re-implementation of glob
    semantics would be a second authority -- but it has a consequence worth
    stating plainly: in an environment without setuptools those tests SKIP,
    and a skipped packaging gate is indistinguishable from a passing one in a
    summary line.  The project virtualenv used to run this suite is exactly
    such an environment (cupy, numpy, netCDF4, pytest; no setuptools), so the
    strongest control on this file's packaging was silently inert wherever it
    mattered most.

    This asserts the DECLARATION rather than the measurement, out of
    ``tomllib`` in the standard library, so it runs everywhere.  The two are
    complementary and neither replaces the other: this one cannot tell you
    that the file actually reaches the wheel, and the setuptools one cannot
    tell you anything at all when setuptools is absent.  Together they fail
    closed in both environments.
    """

    _require_source_tree()

    with PYPROJECT.open("rb") as stream:
        config = tomllib.load(stream)
    excluded = set(
        config["tool"]["setuptools"].get("exclude-package-data", {}).get(
            "gpuwm", []))

    # ``exclude-package-data`` is keyed by package, so the entries are
    # package-relative: ``gpuwm/data/...`` on disk is ``data/...`` here.
    forbidden = {
        Path(relative).relative_to("gpuwm").as_posix()
        for relative in _REDISTRIBUTED_WRF_DATA
    }
    still_excluded = sorted(forbidden & excluded)
    assert still_excluded == [], (
        "pyproject.toml excludes a file this repository declares it DOES "
        f"redistribute: {still_excluded}\n"
        "Remove each from [tool.setuptools.exclude-package-data] under the "
        "'gpuwm' key. Leaving the entry in place ships an mp_physics=28 that "
        "fails closed on a missing activation table for every user, while "
        "thompson_aerosol_contract.AEROSOL_ASSET_REDISTRIBUTED claims "
        "otherwise."
    )


def test_license_metadata_is_an_spdx_expression_not_the_pasted_text() -> None:
    """``pip show gpuwm`` must answer ``Apache-2.0``, not 202 pasted lines.

    ``license = { file = "LICENSE" }`` inlines the whole Apache-2.0 text
    into the METADATA ``License`` field -- the first field run of the
    published wheel got a screenful from ``pip show``.  PEP 639 spells
    the fix: ``license`` is the SPDX expression, ``license-files`` ships
    the actual texts in the wheel, and no deprecated ``License ::``
    classifier restates either.  setuptools grew that reading at 77, so
    the build floor must sit there too or an isolated build with an
    older backend ships the old flood again.
    """

    _require_source_tree()

    with PYPROJECT.open("rb") as stream:
        config = tomllib.load(stream)

    project = config["project"]
    assert project["license"] == "Apache-2.0", (
        "project.license must be the bare SPDX expression string; a table "
        "(file= or text=) puts the whole license text into `pip show`")

    shipped = project.get("license-files", [])
    assert shipped == ["LICENSE", "NOTICE"], shipped
    for name in shipped:
        assert (REPO_ROOT / name).is_file(), (
            f"pyproject names a license file that does not exist: {name}")

    # PEP 639 deprecates License classifiers, and setuptools >=77 refuses
    # to combine one with an SPDX expression -- a re-added classifier is a
    # broken release cut, not a cosmetic nit.
    stray = [entry for entry in project.get("classifiers", [])
             if entry.startswith("License ::")]
    assert stray == [], stray

    # The floor that makes all of the above real in an isolated build.
    requires = config["build-system"]["requires"]
    assert any(entry.replace(" ", "").startswith("setuptools>=")
               and float(entry.replace(" ", "").split(">=")[1]) >= 77
               for entry in requires), requires

    # And the legacy spelling must not linger to fight the PEP 639 one.
    assert "license-files" not in config.get("tool", {}).get(
        "setuptools", {}), (
        "[tool.setuptools] license-files duplicates [project] license-files")
