"""The air-gapped Rust build, proved as a property rather than a habit.

The reopening battery could not build the tree's own HRRR decoder offline
and read the failure -- ``no matching package named 'chrono' found`` -- as a
gap in the vendored registry.  It is not: ``chrono 0.4.45`` has been vendored
and tracked since the baseline commit, and ``cargo build --release --locked
--offline`` succeeds *from inside* ``tools/grib1_bridge``.

The real defect is one directory up.  Cargo discovers ``.cargo/config.toml``
-- which is where the crates.io -> ``vendor/crates-io`` source replacement
lives -- by walking UP from the **working directory**, never from
``--manifest-path``.  So a build driven from the repository root silently
bypasses the vendored registry and resolves against crates.io, which on an
air-gapped box fails naming whichever crate the resolver reached first.  That
is exactly what ``tools/prepare_hrrr_wrf.py``'s decoder auto-build,
``tools/prepare_hrrr_500_native.sh`` and ``docs/benchmark.md`` used to do,
while README/install.sh/install.ps1/CONTRIBUTING all ``cd`` into the crate --
which is why every other Rust target built cleanly and this one did not.

Two properties are bound here, because the wrong diagnosis was still a real
report and both halves have to stay true: the vendored registry is complete
for every locked dependency, and no shipped build path builds a vendored
workspace from outside it.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[1]

#: Every vendored cargo workspace in the tree, in VENDOR.md's terms: a
#: ``Cargo.lock``, a ``.cargo/config.toml`` source replacement, and a
#: ``vendor/crates-io`` directory generated by ``cargo vendor``.
#:
#: ``tools/rw_wps`` -- the mapped decode engine and the rw-wps CLI, the
#: workspace the release build and doctor's remedy text both name -- was
#: absent from this tuple until 2.5.0, and it is the one a reviewer
#: reported as unbuildable offline (locked ``clap 4.6.6`` against a
#: mirror they read as carrying 4.6.1).  The report did not reproduce,
#: but the reason it COULD not have been caught here is real and is
#: fixed below: the workspace was unlisted, and the check was
#: version-blind.
_WORKSPACES = ("tools/grib1_bridge", "tools/rustwx", "tools/rw_wps")

_PACKAGE_NAME = re.compile(r'^name = "(?P<name>[^"]+)"', re.M)
_PACKAGE_VERSION = re.compile(r'^version = "(?P<version>[^"]+)"', re.M)
_PACKAGE_SOURCE = re.compile(r'^source = "(?P<source>[^"]+)"', re.M)


def _locked_external_packages(workspace: Path) -> list[tuple[str, str]]:
    """``(name, version)`` in ``Cargo.lock`` that come from outside the tree.

    A package with no ``source`` is a path member of the workspace itself
    and is not vendored; everything else -- crates.io and git alike -- is
    what ``cargo vendor`` writes into ``vendor/crates-io``.

    The VERSION is carried because it is the half that goes wrong
    silently.  A mirror missing a crate outright fails loudly at the
    first offline build; a mirror carrying the same crate at the WRONG
    version satisfies a name-only check and still makes ``cargo build
    --offline`` resolve nothing -- and ``--offline`` is the shipped
    release invocation and the remedy doctor prints.
    """

    text = (workspace / "Cargo.lock").read_text(encoding="utf-8")
    packages = []
    for block in text.split("[[package]]")[1:]:
        name = _PACKAGE_NAME.search(block)
        version = _PACKAGE_VERSION.search(block)
        source = _PACKAGE_SOURCE.search(block)
        if name and source:
            packages.append((name.group("name"),
                             version.group("version") if version else ""))
    return packages


def _vendored_version(registry: Path, name: str, version: str) -> str | None:
    """The version this mirror actually carries for ``name``, or ``None``.

    ``cargo vendor`` writes bare ``<name>/`` directories by default and
    ``<name>-<version>/`` under ``--versioned-dirs``; the tree ships both
    layouts (``tools/rw_wps`` is versioned, the other two are not), so
    both are read here rather than one being declared canonical.  Either
    way the answer comes from the vendored ``Cargo.toml``, never from the
    directory name -- the name is a label, the manifest is the package.
    """

    import tomllib

    for candidate in (registry / f"{name}-{version}", registry / name):
        manifest = candidate / "Cargo.toml"
        if not manifest.is_file():
            continue
        if not (candidate / ".cargo-checksum.json").is_file():
            continue
        package = tomllib.loads(
            manifest.read_text(encoding="utf-8")).get("package", {})
        return str(package.get("version", ""))
    return None


@pytest.mark.parametrize("relative", _WORKSPACES)
def test_every_locked_dependency_is_vendored(relative: str) -> None:
    workspace = _ROOT / relative
    replacement = (workspace / ".cargo" / "config.toml").read_text(
        encoding="utf-8")
    assert 'replace-with = "vendored-sources"' in replacement
    assert 'directory = "vendor/crates-io"' in replacement

    registry = workspace / "vendor" / "crates-io"
    locked = _locked_external_packages(workspace)
    assert locked, f"{relative} locks no external dependency"
    unresolvable = []
    for name, version in locked:
        vendored = _vendored_version(registry, name, version)
        if vendored is None:
            unresolvable.append(f"{name} {version} (absent)")
        elif vendored != version:
            unresolvable.append(f"{name} {version} (mirror has {vendored})")
    assert not unresolvable, (
        f"{relative}/vendor/crates-io cannot serve {sorted(unresolvable)}, "
        "so `cargo build --locked --offline` resolves nothing there; "
        "regenerate it with `cargo vendor --locked vendor/crates-io` and "
        "record the change in VENDOR.md")


def test_the_vendored_registry_check_can_fail(tmp_path: Path) -> None:
    """The control, on both axes: absent crate AND wrong version.

    The second axis is the one the old name-only check could not see,
    and it is the shape a reviewer reported against ``tools/rw_wps``.
    """

    registry = tmp_path / "crate" / "vendor" / "crates-io"
    for directory, version in (("present", "1.2.3"), ("skewed", "4.6.1")):
        (registry / directory).mkdir(parents=True)
        (registry / directory / ".cargo-checksum.json").write_text(
            "{}", encoding="utf-8")
        (registry / directory / "Cargo.toml").write_text(
            f'[package]\nname = "{directory}"\nversion = "{version}"\n',
            encoding="utf-8")
    (tmp_path / "crate" / "Cargo.lock").write_text(
        '[[package]]\nname = "present"\nversion = "1.2.3"\n'
        'source = "registry+x"\n\n'
        '[[package]]\nname = "skewed"\nversion = "4.6.6"\n'
        'source = "registry+x"\n\n'
        '[[package]]\nname = "absent"\nversion = "0.1.0"\n'
        'source = "registry+x"\n',
        encoding="utf-8")

    locked = _locked_external_packages(tmp_path / "crate")
    assert locked == [("present", "1.2.3"), ("skewed", "4.6.6"),
                      ("absent", "0.1.0")]
    assert _vendored_version(registry, "present", "1.2.3") == "1.2.3"
    assert _vendored_version(registry, "skewed", "4.6.6") == "4.6.1"
    assert _vendored_version(registry, "absent", "0.1.0") is None


#: Files that tell a user or a script how to build a vendored workspace.
#: Handoff reports are excluded: they record what was run, not what to run.
_BUILD_SITES = (
    "tools/prepare_hrrr_wrf.py",
    "tools/prepare_hrrr_500_native.sh",
    "tools/prepare_hrrr_native.sh",
    "docs/benchmark.md",
    "docs/install.md",
    "docs/public/FIRST-LIGHT.md",
    "README.md",
    "CONTRIBUTING.md",
    "install.sh",
    "install.ps1",
)


def test_no_shipped_build_path_bypasses_the_vendored_registry() -> None:
    """``--manifest-path`` into a vendored workspace defeats ``--offline``.

    The build must be driven from inside the crate, because that is the
    only place cargo looks for the source replacement.
    """

    offenders = []
    for relative in _BUILD_SITES:
        path = _ROOT / relative
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for workspace in _WORKSPACES:
            crate = workspace.rsplit("/", 1)[-1]
            for line_number, line in enumerate(text.splitlines(), 1):
                if line.lstrip().startswith("#"):
                    continue
                if "manifest-path" in line and crate in line:
                    offenders.append(f"{relative}:{line_number}")
    assert not offenders, (
        "these build sites reach a vendored cargo workspace through "
        f"--manifest-path and cannot build air-gapped: {offenders}; use "
        "`cd <crate> && cargo build --release --locked --offline`")
