"""Bind the registry generator to the registry file it is supposed to produce.

``gpuwm/physics_registry_v2.json`` is generated by ``tools/build_registry.py``
and hand-edited by whoever corrects a claim.  Nothing forced the two to agree,
so they drifted: the builder wrote its citations from a search that counted a
docstring mention as a read, and replaying it reverted every citation the last
registry fix had just corrected.  The byte-for-byte test below is what makes
that drift impossible to land unnoticed.

The builder also used to write the registry at module scope, so ``import
tools.build_registry`` was enough to clobber a tracked file.  That is asserted
here too, in a subprocess, because an import inside this process would already
have happened before the assertion ran.

Scope, stated plainly: the builder transforms the registry rather than
generating it.  Its tables own the parameter declarations it lists, their
citations, the two nest override columns and two authority sentences; the
components, the templates and the other declarers' parameter rows have no
source in the builder and are carried through from the file.  So this is a
fixpoint gate over the region the builder owns -- perturb a byte there and the
tests below fail, perturb a byte outside it and they cannot see it.  That is
the region the drift happened in.

Every test writes only under ``tmp_path``.  The tracked registry's digest is
checked before and after each subprocess so a regression that reintroduces the
write is reported as a defect rather than silently applied to the tree.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "gpuwm" / "physics_registry_v2.json"
BUILDER_PATH = REPO_ROOT / "tools" / "build_registry.py"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.build_registry import (  # noqa: E402
    OWNED,
    consuming_read_candidates,
    find_consuming_read,
    reads_knob,
)
from gpuwm.physics_registry import physics_registry  # noqa: E402


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _run(*arguments: str) -> subprocess.CompletedProcess[str]:
    """Run a Python command from the repo root and require it to succeed."""

    environment = dict(os.environ)
    environment["PYTHONPATH"] = str(REPO_ROOT)
    completed = subprocess.run(
        [sys.executable, *arguments],
        cwd=REPO_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        timeout=600,
    )
    assert completed.returncode == 0, (
        f"{arguments} failed ({completed.returncode})\n"
        f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}")
    return completed


def test_importing_the_builder_writes_nothing() -> None:
    before = _digest(REGISTRY_PATH)
    _run("-c", "import tools.build_registry")
    assert _digest(REGISTRY_PATH) == before, (
        "importing tools.build_registry rewrote the tracked registry; the "
        "write belongs to main(), not to module scope")


def test_the_builder_reproduces_the_tracked_registry_byte_for_byte(
    tmp_path: Path,
) -> None:
    """The generator and the generated file must not be able to disagree.

    Run into a temporary path -- never over the tracked file -- so a
    disagreement is reported instead of applied.
    """

    before = _digest(REGISTRY_PATH)
    generated = tmp_path / "physics_registry_v2.json"
    _run(str(BUILDER_PATH), "--out", str(generated))

    assert _digest(REGISTRY_PATH) == before, (
        "the builder wrote the tracked registry even though --out named "
        "another path")
    expected = REGISTRY_PATH.read_bytes()
    actual = generated.read_bytes()
    if actual != expected:
        first = next(
            (index for index, (left, right)
             in enumerate(zip(expected, actual)) if left != right),
            min(len(expected), len(actual)))
        pytest.fail(
            "tools/build_registry.py no longer reproduces "
            "gpuwm/physics_registry_v2.json: they first differ at byte "
            f"{first} ({len(expected)} tracked bytes vs {len(actual)} "
            f"generated).\ntracked  ...{expected[first:first + 120]!r}\n"
            f"generated...{actual[first:first + 120]!r}\n"
            "Whichever is right, land the builder change and the registry "
            "change together.")


#: A declaration whose whole spec the builder's own table pins, so its default
#: is one byte the builder rewrites unconditionally.
_OWNED_ROW = b'"num_soil_layers":{'
_DEFAULT_KEY = b'"default":'


def _perturb_one_owned_byte(tracked: bytes) -> bytes:
    """Change the declared default of an owned row, one byte, nothing else."""

    row = tracked.index(_OWNED_ROW)
    index = tracked.index(_DEFAULT_KEY, row) + len(_DEFAULT_KEY)
    digit = tracked[index:index + 1]
    assert digit.isdigit(), (
        f"expected a single-digit default at byte {index}, found {digit!r}")
    return tracked[:index] + (b"4" if digit == b"5" else b"5") \
        + tracked[index + 1:]


def test_the_builder_corrects_a_single_changed_byte_it_owns(
    tmp_path: Path,
) -> None:
    """Negative control: the gate above must be able to fail.

    Feeding the builder a registry whose declared default was edited by one
    byte must produce the tracked bytes back, which is only true if the
    builder is the authority for that field.  It also shows the comparison is
    byte-exact: a check that re-serialised the JSON or compared parsed objects
    would have passed on the citation reversal this gate exists to catch.
    """

    before = _digest(REGISTRY_PATH)
    tracked = REGISTRY_PATH.read_bytes()
    perturbed = _perturb_one_owned_byte(tracked)
    assert len(perturbed) == len(tracked) and perturbed != tracked

    source = tmp_path / "perturbed.json"
    source.write_bytes(perturbed)
    generated = tmp_path / "physics_registry_v2.json"
    _run(str(BUILDER_PATH), "--registry", str(source), "--out", str(generated))

    assert _digest(REGISTRY_PATH) == before
    actual = generated.read_bytes()
    assert actual != perturbed, (
        "the builder carried a one-byte edit of a field it declares straight "
        "through, so the byte-identity gate cannot see drift in it")
    assert actual == tracked, (
        "the builder neither reproduced nor corrected the perturbed default")


@pytest.mark.parametrize("name", sorted(OWNED))
def test_every_citation_the_builder_owns_resolves(name: str) -> None:
    """A citation this builder claims must satisfy the shipped claim gate."""

    citation = physics_registry()["parameters"][name].get("consuming_read")
    assert isinstance(citation, str) and citation, (
        f"{name}: the builder claims this row, so it must cite a read")
    assert reads_knob(citation, name), (
        f"{name}: {citation} does not read it in executable code")


def test_a_docstring_only_mention_is_not_a_candidate() -> None:
    """The defect this builder shipped: prose counted as a read.

    ``gpuwm/core/mynn_surface.py`` used to name both surface-layer knobs in
    its module docstring and nowhere else, which is why the registry stopped
    citing it.  A builder that still accepted it would repoint them back on
    the next run.

    ``isftcflx`` is no longer one of those two: the over-water branches are
    ported, so that file now reads it in executable code and is a legitimate
    candidate.  ``iz0tlnd`` is still land-only and still prose there, which is
    what keeps this regression test honest -- it is asserting that the builder
    can tell prose from code, not that this particular file is inert.
    """

    prose_only = "gpuwm/core/mynn_surface.py"
    assert (REPO_ROOT / prose_only).is_file()
    assert prose_only not in consuming_read_candidates("iz0tlnd")
    assert not reads_knob(prose_only, "iz0tlnd")
    assert find_consuming_read("iz0tlnd", prose_only) != prose_only
    # ...and the same file IS a candidate for the knob it now consumes, so a
    # builder that stopped distinguishing them fails here too.
    assert prose_only in consuming_read_candidates("isftcflx")
    assert reads_knob(prose_only, "isftcflx")


def test_the_configuration_module_can_be_cited() -> None:
    """``gpuwm/config.py`` was excluded outright and had to be reachable.

    ``num_soil_layers`` is validated there and consumed nowhere else, so a
    search that could never name the file could never produce the registry's
    own citation.
    """

    candidates = consuming_read_candidates("num_soil_layers")
    assert "gpuwm/config.py" in candidates
    assert find_consuming_read("num_soil_layers", "gpuwm/config.py") == (
        "gpuwm/config.py")


def test_an_executable_read_outranks_a_string_literal_mention() -> None:
    """A namelist table spells a knob without reading it.

    ``gpuwm/core/ruc_contract.py`` carries ``num_soil_layers`` only as a dict
    key, pinned to the unported nine-layer geometry.  Prose stripping cannot
    remove it -- a string literal can be a real read -- so the ranking has to
    place it below a file that reads the knob as an identifier.
    """

    candidates = consuming_read_candidates("num_soil_layers")
    string_only = "gpuwm/core/ruc_contract.py"
    assert string_only in candidates
    assert candidates.index("gpuwm/config.py") < candidates.index(string_only)


def test_a_verified_citation_survives_a_lower_ranked_competitor() -> None:
    """The search proposes; it does not overrule a citation that still holds.

    Several files read ``moist``, and only one is the component that acts on
    it.  That is a judgement made by reading code, so the builder keeps the
    citation already in the registry as long as it resolves.
    """

    tracked = physics_registry()["parameters"]["moist"]["consuming_read"]
    assert find_consuming_read("moist", tracked) == tracked
    assert find_consuming_read("moist", None) in consuming_read_candidates(
        "moist")


def test_a_citation_that_stopped_resolving_is_replaced() -> None:
    """A claim cannot outlive the read that justified it."""

    replacement = find_consuming_read("km_opt", "gpuwm/core/kernels")
    assert replacement is not None
    assert replacement != "gpuwm/core/kernels"
    assert reads_knob(replacement, "km_opt")
