"""Move every declaration of the release version in one step.

THE BREAKAGE THIS PREVENTS: the release number is declared in four files
that nothing ties together at edit time: ``pyproject.toml`` (the project
version and the ``gpuwm-data==`` pin), ``gpuwm-data/gpuwm_data/VERSION``
(the data package, which the engine requires at exactly its own version),
and the terminal crate's ``Cargo.toml`` and ``Cargo.lock``. Opening 2.7.4
by hand moved the first two and missed the terminal, so the release contract
set failed on ``test_terminal_and_python_release_versions_agree`` and the
candidate was not cuttable until a second commit. This tool rewrites all four
together, opens the changelog section for the new number, and ``--check``
reports any file that disagrees with ``pyproject.toml``.

It also regenerates the two binary licence notices, which pin the digests of
the terminal crate's ``Cargo.toml`` and ``Cargo.lock``. Opening 2.8.0 moved
both files and left the notices naming the old digests, so
``tests/test_licence_notices_ship.py`` refused every commit on the line until
the notice was regenerated by hand. The Zarr reader's notice reproduces that
binary notice whole, as the retained record of the mapped engine it links, so
it is regenerated straight after: it shipped through 2.8.4 reproducing the
binary notice of 2026-09-08, which by then counted 27 binaries in a bundle
of 31.

And it re-pins the shared UI vendor manifest's digest of the terminal
crate's ``Cargo.lock``. The manifest pins that digest so a lock edited
outside a re-vendor is caught, and the version line is the one edit this
tool makes to the lock. Opening 2.7.5, 2.7.6 and 2.8.0 each left the old
digest behind, so ``tests/test_vendored_cargo_registry.py`` refused the new
line until a second commit re-pinned it by hand.

Usage:
  python tools/release/bump_version.py --to 2.7.5    # rewrite, open the changelog section
  python tools/release/bump_version.py --check       # exit 1 naming any file out of step
Exit 0 = every declaration agrees (or was moved); 1 = a declaration disagrees; 2 = usage.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

VERSION = re.compile(r"^\d+\.\d+\.\d+$")

#: Relative path, the pattern whose group 1 is the version, how many matches the file must carry.
DECLARATIONS = (
    ("pyproject.toml", re.compile(r'^version = "(\d+\.\d+\.\d+)"$', re.M), 1),
    ("pyproject.toml", re.compile(r'"gpuwm-data==(\d+\.\d+\.\d+)"'), 1),
    ("gpuwm-data/gpuwm_data/VERSION", re.compile(r"^(\d+\.\d+\.\d+)\s*$"), 1),
    ("tools/arwen-tui/Cargo.toml", re.compile(r'^version = "(\d+\.\d+\.\d+)"$', re.M), 1),
    ("tools/arwen-tui/Cargo.lock", re.compile(r'name = "arwen-tui"\nversion = "(\d+\.\d+\.\d+)"'), 1),
)

CHANGELOG = "CHANGELOG.md"

#: The generator of the two binary licence notices, and the notices it writes.
NOTICE_TOOL = "tools/update_tui_license_notice.py"
NOTICES = ("licenses/THIRD-PARTY-LICENSES-bridge-binaries.txt",
           "tools/rustwx/assets/basemap/THIRD-PARTY-LICENSES.txt")

#: The generator of the Zarr reader's notices, the notices it writes, and the
#: lock it resolves. It reads the binary notice above, so it runs after it.
ZARR_NOTICE_TOOL = "tools/update_zarr_license_notice.py"
ZARR_NOTICES = ("licenses/THIRD-PARTY-LICENSES-zarr-binary.txt",
                "tools/rustwx/assets/basemap/THIRD-PARTY-LICENSES-zarr-binary.txt")
ZARR_LOCK = "tools/zarr_bridge/Cargo.lock"

#: The shared UI vendor manifest, which pins the terminal lock's digest, and
#: the lock it pins under the workspace name ``arwen-tui``.
VENDOR_MANIFEST = "tools/arwen-ui-vendor/manifest.json"
TERMINAL_LOCK = "tools/arwen-tui/Cargo.lock"
VENDOR_LOCK_PIN = re.compile(r'("arwen-tui":\s*")([0-9a-f]{64})(")')


def declared(root: Path) -> list[tuple[str, str]]:
    """Every (file, version) declaration in the tree, in DECLARATIONS order."""
    found = []
    for relative, pattern, count in DECLARATIONS:
        text = (root / relative).read_text(encoding="utf-8")
        matches = pattern.findall(text)
        if len(matches) != count:
            raise SystemExit(f"bump_version: {relative} carries {len(matches)} version declarations, expected {count}")
        found.extend((relative, m) for m in matches)
    return found


def disagreements(root: Path) -> list[str]:
    found = declared(root)
    lead = found[0][1]
    return [f"{relative} says {version}, pyproject.toml says {lead}" for relative, version in found if version != lead]


def _rewrite(path: Path, pattern: re.Pattern, to: str) -> None:
    text = path.read_bytes().decode("utf-8")

    def sub(match: re.Match) -> str:
        whole = match.group(0)
        start = match.start(1) - match.start(0)
        end = match.end(1) - match.start(0)
        return whole[:start] + to + whole[end:]

    path.write_bytes(pattern.sub(sub, text).encode("utf-8"))


def open_changelog(root: Path, to: str) -> bool:
    """Insert ``## <to> (unreleased)`` at the head unless a section for it exists."""
    path = root / CHANGELOG
    text = path.read_bytes().decode("utf-8")
    if re.search(rf"^## {re.escape(to)}\b", text, re.M):
        return False
    newline = "\r\n" if "\r\n" in text else "\n"
    section = f"## {to} (unreleased){newline}{newline}New:{newline}{newline}Fixed:{newline}{newline}"
    head = re.match(r"# Changelog\r?\n\r?\n", text)
    if not head:
        raise SystemExit("bump_version: CHANGELOG.md does not start with '# Changelog'")
    path.write_bytes((text[: head.end()] + section + text[head.end():]).encode("utf-8"))
    return True


def bump(root: Path, to: str) -> list[str]:
    if not VERSION.match(to):
        raise SystemExit(f"bump_version: --to wants MAJOR.MINOR.PATCH, got {to!r}")
    declared(root)  # refuses a tree whose declarations are not where this tool expects them
    touched = []
    for relative, pattern, _ in DECLARATIONS:
        _rewrite(root / relative, pattern, to)
        if relative not in touched:
            touched.append(relative)
    if open_changelog(root, to):
        touched.append(CHANGELOG)
    touched.extend(refresh_terminal_notices(root))
    touched.extend(repin_vendor_lock(root))
    return touched


def repin_vendor_lock(root: Path) -> list[str]:
    """Pin the terminal lock's new digest in the shared UI vendor manifest.

    Only the digest moves: the bump changes the lock's own version line and
    no dependency, so the vendored crates stay what the manifest lists. A
    tree without the manifest (a partial copy) has nothing to keep in step.
    """
    manifest = root / VENDOR_MANIFEST
    if not manifest.is_file():
        return []
    digest = hashlib.sha256((root / TERMINAL_LOCK).read_bytes()).hexdigest()
    text = manifest.read_bytes().decode("utf-8")
    found = VENDOR_LOCK_PIN.findall(text)
    if len(found) != 1:
        raise SystemExit(f"bump_version: {VENDOR_MANIFEST} carries {len(found)} arwen-tui lock digests, expected 1")
    if found[0][1] == digest:
        return []
    manifest.write_bytes(VENDOR_LOCK_PIN.sub(lambda match: match.group(1) + digest + match.group(3), text)
                         .encode("utf-8"))
    return [VENDOR_MANIFEST]


def refresh_terminal_notices(root: Path) -> list[str]:
    """Regenerate the notices that pin the terminal crate's manifest digests.

    The binary notice first, then the Zarr reader's notice, which reproduces
    the binary notice and would otherwise keep the copy from before the bump.
    A tree without a generator or its inputs (a partial copy) has no notices
    to keep in step, so nothing is done for that generator there.
    """
    tool = root / NOTICE_TOOL
    if not tool.is_file() or not all((root / notice).is_file() for notice in NOTICES):
        return []
    subprocess.run([sys.executable, str(tool)], cwd=root, check=True)
    touched = list(NOTICES)
    zarr = root / ZARR_NOTICE_TOOL
    if zarr.is_file() and all((root / path).is_file() for path in (ZARR_LOCK, *ZARR_NOTICES)):
        subprocess.run([sys.executable, str(zarr)], cwd=root, check=True)
        touched.extend(ZARR_NOTICES)
    return touched


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--to", help="the version every declaration moves to")
    parser.add_argument("--check", action="store_true", help="report declarations that disagree with pyproject.toml")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args(argv)
    if bool(args.to) == args.check:
        parser.print_usage(sys.stderr)
        return 2
    root = args.root.resolve()
    if args.check:
        wrong = disagreements(root)
        for line in wrong:
            print("bump_version: " + line, file=sys.stderr)
        if wrong:
            return 1
        print(f"bump_version: every declaration says {declared(root)[0][1]}")
        return 0
    touched = bump(root, args.to)
    for relative in touched:
        print(f"bump_version: {relative} -> {args.to}")
    return 1 if disagreements(root) else 0


if __name__ == "__main__":
    raise SystemExit(main())
