//! Weather-family entry points; research configurations share the native catalog.
pub struct Mode {
    pub id: &'static str,
    pub title: &'static str,
    pub subtitle: &'static str,
    pub keywords: &'static str,
    pub preset: &'static str,
    pub chain: &'static str,
    pub hours: &'static str,
    pub setup: &'static str,
    pub guidance: &'static str,
    pub limits: &'static str,
    pub track: bool,
    pub downscale: bool,
    pub scenario: bool,
}

pub const MODES: &[Mode] = &[
    Mode { id: "general", title: "Everyday forecast", subtitle: "A clear first forecast, from region to results",
        keywords: "general beginner first learn weather", preset: "general", chain: "", hours: "6",
        setup: "12 km root · 6 hours · General plots",
        guidance: "Choose a region and UTC cycle. Start with one domain; add finer nests in Domains when you need them. The engine sizes the grid for your GPU.",
        limits: "The source supplies the initial weather. Check and Plan validate the saved configuration before launch.", track: false, downscale: false, scenario: false },
    Mode { id: "supercell", title: "Supercells & severe storms", subtitle: "Storm structure, rotation and a finer child forecast",
        keywords: "supercell massive tornado severe convection thunderstorm hail downscale", preset: "tornado", chain: "3,3", hours: "6",
        setup: "12 → 4 → 1.33 km · 6 hours · Severe plots",
        guidance: "Start a nested forecast, or downscale an archived parent around your storm. For an existing nest, Domains exposes rotation/echo tracking and explicit birth/retirement criteria.",
        limits: "Grid spacing is an editable starting point, not a tornado forecast. Archived downscaling requires the parent's physics evidence and an explicit boundary-cadence choice.", track: true, downscale: true, scenario: false },
    Mode { id: "tropical", title: "Hurricanes & tropical weather", subtitle: "Pressure, wind, rain and storm-following nests",
        keywords: "hurricane cyclone typhoon tropical track vortex", preset: "hurricane", chain: "3", hours: "12",
        setup: "12 → 4 km · 12 hours · Tropical plots",
        guidance: "Cover the storm and its expected path with the parent domain. Open Tracking for an existing child nest to review the pressure-vortex search. Track-file output remains available in complete TOML settings.",
        limits: "A tropical plot set does not create a cyclone or enable tracking. Those depend on the initial state and the explicit domain settings.", track: true, downscale: true, scenario: false },
    Mode { id: "hypothetical_tropical", title: "Hypothetical hurricane lab", subtitle: "Explore a clearly labelled what-if storm scenario",
        keywords: "fantasy fictional hypothetical hurricane scenario what if experiment alternate", preset: "hurricane", chain: "3", hours: "12",
        setup: "Scenario workspace · tropical plots · explicit source and cycle",
        guidance: "Use your scenario's existing TOML and forcing, or create a labelled starting configuration to edit. Then set a child nest's pressure tracking in Domains. Keep the source run for comparison.",
        limits: "This workspace does not insert or relocate a hurricane. A new configuration begins from its chosen source; changed weather must come from your actual scenario inputs and supported settings.", track: true, downscale: true, scenario: true },
    Mode { id: "winter", title: "Snow, ice & blizzards", subtitle: "Precipitation type, temperature and strong winter winds",
        keywords: "winter blizzard snow ice freezing sleet lake effect", preset: "snow", chain: "3", hours: "12",
        setup: "12 → 4 km · 12 hours · Winter plots",
        guidance: "Include the storm's approach and terrain in your region. Review the temperature profile, precipitation type and wind together; extend the run window explicitly when needed.",
        limits: "Snow and accumulation products depend on saved fields and valid output times. Blowing-snow visibility is not implied by this mode.", track: false, downscale: true, scenario: false },
    Mode { id: "flood", title: "Heavy rain & flooding", subtitle: "Rainfall totals, moisture transport and storm evolution",
        keywords: "rain flood flooding atmospheric river monsoon rainfall", preset: "rain", chain: "3", hours: "12",
        setup: "12 → 4 km · 12 hours · Rain plots",
        guidance: "Include the upstream moisture source and the whole area of interest. Compare total rainfall with time-window accumulations and the storm's motion.",
        limits: "Rainfall is atmospheric output. River flow, inundation and flood depth require a separate hydrologic model.", track: false, downscale: true, scenario: false },
    Mode { id: "fire", title: "Fire weather", subtitle: "Dry air, gusts, heat and terrain-driven flow",
        keywords: "fire wildfire smoke red flag dry humidity fuel", preset: "fire", chain: "3", hours: "6",
        setup: "12 → 4 km · 6 hours · Fire-weather plots",
        guidance: "Place terrain and upwind flow inside the domain. Inspect humidity, temperature, sustained wind and gusts through the period of interest.",
        limits: "Atmospheric fire weather only: this mode does not simulate ignition, fuel moisture, wildfire spread or smoke transport.", track: false, downscale: true, scenario: false },
    Mode { id: "wind", title: "Wind & damaging gusts", subtitle: "Surface flow, pressure gradients and peak winds",
        keywords: "wind gust derecho squall gale damaging downslope", preset: "wind", chain: "3", hours: "6",
        setup: "12 → 4 km · 6 hours · Wind plots",
        guidance: "Include terrain and the upstream pressure pattern. Examine gusts alongside resolved flow and storm structure; add a finer child where justified.",
        limits: "Gust diagnostics and grid-scale wind differ. This mode does not resolve the wind around individual buildings.", track: false, downscale: true, scenario: false },
    Mode { id: "temperature", title: "Heat, cold & frost", subtitle: "Near-surface temperature, moisture and overnight change",
        keywords: "temperature heat cold frost freeze hot wave agriculture", preset: "temperature", chain: "", hours: "12",
        setup: "12 km root · 12 hours · Temperature plots",
        guidance: "Choose a UTC start and duration spanning the daytime peak or overnight minimum. Add local terrain detail if your question needs it.",
        limits: "Surface diagnostics describe model grid cells; local shelter, irrigation and urban effects may be unresolved.", track: false, downscale: false, scenario: false },
    Mode { id: "aviation", title: "Clouds, fog & aviation weather", subtitle: "Cloud structure, moisture and winds aloft",
        keywords: "aviation fog clouds cloud ceiling flight visibility airport", preset: "aviation", chain: "3", hours: "6",
        setup: "12 → 4 km · 6 hours · Cloud and wind plots",
        guidance: "Explore cloud cover, low-level saturation and winds through the atmosphere. Keep your full route or region within the parent domain.",
        limits: "Research weather fields, not flight clearance or a certified ceiling/visibility forecast. This mode does not add an icing model.", track: false, downscale: false, scenario: false },
    Mode { id: "terrain", title: "Mountains & local terrain", subtitle: "Orographic rain, valley conditions and downslope flow",
        keywords: "mountain terrain valley orographic downslope foehn alpine", preset: "terrain", chain: "3", hours: "6",
        setup: "12 → 4 km · 6 hours · Terrain-weather plots",
        guidance: "Include the upstream slope, crest and downstream area. Use Geography to select actual terrain data, and Domains to review a finer child.",
        limits: "A finer requested grid does not improve the underlying terrain data. Inspect the actual preparation and resolved topography.", track: false, downscale: true, scenario: false },
    Mode { id: "coastal", title: "Coasts & sea breezes", subtitle: "Land-sea contrasts, coastal wind and convection",
        keywords: "coast coastal marine sea breeze lake shore sea fog", preset: "coastal", chain: "3", hours: "12",
        setup: "12 → 4 km · 12 hours · Coastal-weather plots",
        guidance: "Keep land, coastline and offshore flow in the region. Span the heating cycle to inspect a sea breeze; review the source's surface state.",
        limits: "Atmospheric coastal weather only. This mode does not model tides, storm surge or ocean waves.", track: false, downscale: false, scenario: false },
];

pub fn mode(id: &str) -> Option<&'static Mode> { MODES.iter().find(|mode| mode.id == id) }


#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Route { New, Open, CurrentPlots, Render, Downscale, Tracking, Scenario }
pub enum Intent { Keep, Close, Start(usize, Route), StartConfig(usize, Route) }
pub use crate::research_browser::Browser;
