! Service metadata for chem/module_dep_simple.F:88-91,1626-1628,4198-4201.
module module_state_description
 implicit none
 integer, parameter :: num_chem=9,num_moist=4,param_first_scalar=2
 integer :: p_aacd=1
 integer :: p_acbzo2=1
 integer :: p_acet=1
 integer :: p_aceto2=1
 integer :: p_acetol=1
 integer :: p_acetp=1
 integer :: p_aco3=1
 integer :: p_ald=1
 integer :: p_ald2=1
 integer :: p_aldx=1
 integer :: p_alk1=1
 integer :: p_alk3=1
 integer :: p_alk4=1
 integer :: p_alk5=1
 integer :: p_alkh=1
 integer :: p_alkhaer1=1
 integer :: p_alknit=1
 integer :: p_alko2=1
 integer :: p_alkooh=1
 integer :: p_anhy=1
 integer :: p_ano2=1
 integer :: p_ant1_c=1
 integer :: p_ant1_o=1
 integer :: p_ant2_c=1
 integer :: p_ant2_o=1
 integer :: p_ant3_c=1
 integer :: p_ant3_o=1
 integer :: p_ant4_c=1
 integer :: p_ant4_o=1
 integer :: p_api=1
 integer :: p_api1=1
 integer :: p_api2=1
 integer :: p_apin=1
 integer :: p_apinaer1=1
 integer :: p_apinaer2=1
 integer :: p_apinaer3=1
 integer :: p_apinaer4=1
 integer :: p_apinene=1
 integer :: p_arnoh14=1
 integer :: p_arnoh17=1
 integer :: p_aro1=1
 integer :: p_aro2=1
 integer :: p_aroh14=1
 integer :: p_aroh17=1
 integer :: p_bacl=1
 integer :: p_bald=1
 integer :: p_benzene=1
 integer :: p_benzo2=1
 integer :: p_benzooh=1
 integer :: p_bepomuc=1
 integer :: p_bigald1=1
 integer :: p_bigald2=1
 integer :: p_bigald3=1
 integer :: p_bigald4=1
 integer :: p_bigalk=1
 integer :: p_bigene=1
 integer :: p_biog1_c=1
 integer :: p_biog1_o=1
 integer :: p_biog2_c=1
 integer :: p_biog2_o=1
 integer :: p_biog3_c=1
 integer :: p_biog3_o=1
 integer :: p_biog4_c=1
 integer :: p_biog4_o=1
 integer :: p_bpin=1
 integer :: p_bpinaer1=1
 integer :: p_bpinaer2=1
 integer :: p_bpinaer3=1
 integer :: p_bpinaer4=1
 integer :: p_bpinaer5=1
 integer :: p_bpinene=1
 integer :: p_bzald=1
 integer :: p_bzco_o2=1
 integer :: p_bzoo=1
 integer :: p_bzooh=1
 integer :: p_c10h16=1
 integer :: p_c2h2=1
 integer :: p_c2h4=1
 integer :: p_c2h5cho=1
 integer :: p_c2h5co3h=1
 integer :: p_c2h5no3=1
 integer :: p_c2h5o2=1
 integer :: p_c2h5oh=1
 integer :: p_c2h5ooh=1
 integer :: p_c2h6=1
 integer :: p_c2o3=1
 integer :: p_c3h6=1
 integer :: p_c3h6ooh=1
 integer :: p_c3h8=1
 integer :: p_c5h8=1
 integer :: p_c6h5o2=1
 integer :: p_c6h5ooh=1
 integer :: p_c_o2=1
 integer :: p_carb10=1
 integer :: p_carb11a=1
 integer :: p_carb12=1
 integer :: p_carb13=1
 integer :: p_carb14=1
 integer :: p_carb15=1
 integer :: p_carb16=1
 integer :: p_carb17=1
 integer :: p_carb3=1
 integer :: p_carb6=1
 integer :: p_carb7=1
 integer :: p_carb9=1
 integer :: p_ccarb12=1
 integer :: p_ccho=1
 integer :: p_cco_o2=1
 integer :: p_cco_oh=1
 integer :: p_cco_ooh=1
 integer :: p_cdicleth=1
 integer :: p_ch2cl2=1
 integer :: p_ch3ccl3=1
 integer :: p_ch3cho=1
 integer :: p_ch3cl=1
 integer :: p_ch3cn=1
 integer :: p_ch3co2h=1
 integer :: p_ch3cooh=1
 integer :: p_ch3no3=1
 integer :: p_ch3o2=1
 integer :: p_ch3o2no2=1
 integer :: p_ch3oh=1
 integer :: p_ch3oo=1
 integer :: p_ch3ooh=1
 integer :: p_ch3s=1
 integer :: p_ch3sch2oo=1
 integer :: p_ch3so=1
 integer :: p_ch3so2=1
 integer :: p_ch3so2ch2oo=1
 integer :: p_ch3so2h=1
 integer :: p_ch3so2oo=1
 integer :: p_ch3so3=1
 integer :: p_ch4=1
 integer :: p_chcl3=1
 integer :: p_cl=1
 integer :: p_cl2=1
 integer :: p_clno2=1
 integer :: p_clo=1
 integer :: p_co=4
 integer :: p_co2=1
 integer :: p_cooh=1
 integer :: p_cres=1
 integer :: p_cro=1
 integer :: p_csl=1
 integer :: p_cslaer=1
 integer :: p_cvasoa1=1
 integer :: p_cvasoa2=1
 integer :: p_cvasoa3=1
 integer :: p_cvasoa4=1
 integer :: p_cvasoaX=1
 integer :: p_cvbsoa1=1
 integer :: p_cvbsoa2=1
 integer :: p_cvbsoa3=1
 integer :: p_cvbsoa4=1
 integer :: p_cvbsoaX=1
 integer :: p_cxo3=1
 integer :: p_dcb=1
 integer :: p_dcb1=1
 integer :: p_dcb2=1
 integer :: p_dcb3=1
 integer :: p_dicarbo2=1
 integer :: p_DIEN=1
 integer :: p_dime35eb=1
 integer :: p_dms=1
 integer :: p_dmso=1
 integer :: p_dmso2=1
 integer :: p_eneo2=1
 integer :: p_eo=1
 integer :: p_eooh=1
 integer :: p_ete=1
 integer :: p_eth=1
 integer :: p_etha=1
 integer :: p_ethene=1
 integer :: p_ethp=1
 integer :: p_eto2=1
 integer :: p_etoh=1
 integer :: p_etooh=1
 integer :: p_facd=1
 integer :: p_fmcl=1
 integer :: p_form=1
 integer :: p_gly=1
 integer :: p_glyald=1
 integer :: p_h2=1
 integer :: p_h2o2=1
 integer :: p_h2so4=1
 integer :: p_hc3=1
 integer :: p_hc5=1
 integer :: p_hc8=1
 integer :: p_hcho=1
 integer :: p_hcl=1
 integer :: p_hcn=1
 integer :: p_hco3=1
 integer :: p_hcooh=1
 integer :: p_hg0=1
 integer :: p_hg2=1
 integer :: p_HKET=1
 integer :: p_hno3=7
 integer :: p_hno4=1
 integer :: p_ho=1
 integer :: p_ho2=1
 integer :: p_hoc2h4no3=1
 integer :: p_hoc2h4ooh=1
 integer :: p_hoch2ch2o2=1
 integer :: p_hoch2cho=1
 integer :: p_hoch2co3h=1
 integer :: p_hocl=1
 integer :: p_honitr=1
 integer :: p_hono=1
 integer :: p_hpald=1
 integer :: p_hso3=1
 integer :: p_hum=1
 integer :: p_humaer=1
 integer :: p_hydrald=1
 integer :: p_ic3h7no3=1
 integer :: p_ic3h7o2=1
 integer :: p_iepox=1
 integer :: p_iole=1
 integer :: p_ipropol=1
 integer :: p_iso=1
 integer :: p_iso2=1
 integer :: p_isoaer1=1
 integer :: p_isoaer2=1
 integer :: p_isooh=1
 integer :: p_isop=1
 integer :: p_isopao2=1
 integer :: p_isopbo2=1
 integer :: p_isopn=1
 integer :: p_isopnita=1
 integer :: p_isopnitb=1
 integer :: p_isopnooh=1
 integer :: p_isopo2=1
 integer :: p_isopooh=1
 integer :: p_isopp=1
 integer :: p_isopr=1
 integer :: p_isoprd=1
 integer :: p_isoprene=1
 integer :: p_isoprod=1
 integer :: p_ispd=1
 integer :: p_ket=1
 integer :: p_lim=1
 integer :: p_lim1=1
 integer :: p_lim2=1
 integer :: p_limaer1=1
 integer :: p_limaer2=1
 integer :: p_ma_pan=1
 integer :: p_ma_rco3=1
 integer :: p_macr=1
 integer :: p_malo2=1
 integer :: p_mbo=1
 integer :: p_mdialo2=1
 integer :: p_mek=1
 integer :: p_meko2=1
 integer :: p_mekooh=1
 integer :: p_meo2=1
 integer :: p_meoh=1
 integer :: p_mepx=1
 integer :: p_methacro=1
 integer :: p_methtol=1
 integer :: p_mgly=1
 integer :: p_mpan=1
 integer :: p_msa=1
 integer :: p_msia=1
 integer :: p_mtf=1
 integer :: p_mvko2=1
 integer :: p_mvkooh=1
 integer :: p_n2o=1
 integer :: p_n2o5=1
 integer :: p_nap=1
 integer :: p_nc4ch2oh=1
 integer :: p_nc4cho=1
 integer :: p_nc4h10=1
 integer :: p_nh3=6
 integer :: p_no=1
 integer :: p_no2=3
 integer :: p_no3=1
 integer :: p_noa=1
 integer :: p_nphe=1
 integer :: p_npropol=1
 integer :: p_nrn12o2=1
 integer :: p_nrn12ooh=1
 integer :: p_nrn6o2=1
 integer :: p_nrn6ooh=1
 integer :: p_nrn9o2=1
 integer :: p_nrn9ooh=1
 integer :: p_nrtn28o2=1
 integer :: p_nrtn28ooh=1
 integer :: p_nrtx28o2=1
 integer :: p_nrtx28ooh=1
 integer :: p_nru12o2=1
 integer :: p_nru12ooh=1
 integer :: p_nru14o2=1
 integer :: p_nru14ooh=1
 integer :: p_nterpooh=1
 integer :: p_ntr=1
 integer :: p_nucarb12=1
 integer :: p_o=1
 integer :: p_o1d=1
 integer :: p_o1d_cb4=1
 integer :: p_o3=2
 integer :: p_oci=1
 integer :: p_ociaer1=1
 integer :: p_ociaer2=1
 integer :: p_oethtol=1
 integer :: p_ol2=1
 integer :: p_ole=1
 integer :: p_ole1=1
 integer :: p_ole2=1
 integer :: p_oli=1
 integer :: p_olt=1
 integer :: p_onit=1
 integer :: p_onitr=1
 integer :: p_op1=1
 integer :: p_op2=1
 integer :: p_op3=1
 integer :: p_opcg1_b_c=1
 integer :: p_opcg1_b_o=1
 integer :: p_opcg1_f_c=1
 integer :: p_opcg1_f_o=1
 integer :: p_opcg2_b_c=1
 integer :: p_opcg2_b_o=1
 integer :: p_opcg2_f_c=1
 integer :: p_opcg2_f_o=1
 integer :: p_opcg3_b_c=1
 integer :: p_opcg3_b_o=1
 integer :: p_opcg3_f_c=1
 integer :: p_opcg3_f_o=1
 integer :: p_opcg4_b_c=1
 integer :: p_opcg4_b_o=1
 integer :: p_opcg4_f_c=1
 integer :: p_opcg4_f_o=1
 integer :: p_opcg5_b_c=1
 integer :: p_opcg5_b_o=1
 integer :: p_opcg5_f_c=1
 integer :: p_opcg5_f_o=1
 integer :: p_opcg6_b_c=1
 integer :: p_opcg6_b_o=1
 integer :: p_opcg6_f_c=1
 integer :: p_opcg6_f_o=1
 integer :: p_opcg7_b_c=1
 integer :: p_opcg7_b_o=1
 integer :: p_opcg7_f_c=1
 integer :: p_opcg7_f_o=1
 integer :: p_opcg8_b_c=1
 integer :: p_opcg8_b_o=1
 integer :: p_opcg8_f_c=1
 integer :: p_opcg8_f_o=1
 integer :: p_open=1
 integer :: p_ora1=1
 integer :: p_ora2=1
 integer :: p_oxyl=1
 integer :: p_paa=1
 integer :: p_pacd=1
 integer :: p_pah=1
 integer :: p_pahaer1=1
 integer :: p_pahaer2=1
 integer :: p_pan=1
 integer :: p_pan2=1
 integer :: p_panx=1
 integer :: p_par=1
 integer :: p_pbzn=1
 integer :: p_pbznit=1
 integer :: p_pcg1_b_c=1
 integer :: p_pcg1_b_o=1
 integer :: p_pcg1_f_c=1
 integer :: p_pcg1_f_o=1
 integer :: p_pcg2_b_c=1
 integer :: p_pcg2_b_o=1
 integer :: p_pcg2_f_c=1
 integer :: p_pcg2_f_o=1
 integer :: p_pcg3_b_c=1
 integer :: p_pcg3_b_o=1
 integer :: p_pcg3_f_c=1
 integer :: p_pcg3_f_o=1
 integer :: p_pcg4_b_c=1
 integer :: p_pcg4_b_o=1
 integer :: p_pcg4_f_c=1
 integer :: p_pcg4_f_o=1
 integer :: p_pcg5_b_c=1
 integer :: p_pcg5_b_o=1
 integer :: p_pcg5_f_c=1
 integer :: p_pcg5_f_o=1
 integer :: p_pcg6_b_c=1
 integer :: p_pcg6_b_o=1
 integer :: p_pcg6_f_c=1
 integer :: p_pcg6_f_o=1
 integer :: p_pcg7_b_c=1
 integer :: p_pcg7_b_o=1
 integer :: p_pcg7_f_c=1
 integer :: p_pcg7_f_o=1
 integer :: p_pcg8_b_c=1
 integer :: p_pcg8_b_o=1
 integer :: p_pcg8_f_c=1
 integer :: p_pcg8_f_o=1
 integer :: p_pcg9_b_c=1
 integer :: p_pcg9_b_o=1
 integer :: p_pcg9_f_c=1
 integer :: p_pcg9_f_o=1
 integer :: p_pethtol=1
 integer :: p_phan=1
 integer :: p_phen=1
 integer :: p_pheno=1
 integer :: p_pheno2=1
 integer :: p_phenol=1
 integer :: p_phenooh=1
 integer :: p_pna=1
 integer :: p_po2=1
 integer :: p_ppn=1
 integer :: p_pro2=1
 integer :: p_prod2=1
 integer :: p_prooh=1
 integer :: p_qc=3
 integer :: p_qr=4
 integer :: p_qv=2
 integer :: p_r2o2=1
 integer :: p_ra13no3=1
 integer :: p_ra13o2=1
 integer :: p_ra13ooh=1
 integer :: p_ra16no3=1
 integer :: p_ra16o2=1
 integer :: p_ra16ooh=1
 integer :: p_ra19ao2=1
 integer :: p_ra19co2=1
 integer :: p_ra19no3=1
 integer :: p_ra19ooh=1
 integer :: p_ra22ao2=1
 integer :: p_ra22bo2=1
 integer :: p_ra22no3=1
 integer :: p_ra22ooh=1
 integer :: p_ra25no3=1
 integer :: p_ra25o2=1
 integer :: p_ra25ooh=1
 integer :: p_raroh14=1
 integer :: p_raroh17=1
 integer :: p_rcho=1
 integer :: p_rco_o2=1
 integer :: p_rco_oh=1
 integer :: p_rco_ooh=1
 integer :: p_rcooh25=1
 integer :: p_rn10no3=1
 integer :: p_rn10o2=1
 integer :: p_rn10ooh=1
 integer :: p_rn11o2=1
 integer :: p_rn11ooh=1
 integer :: p_rn12no3=1
 integer :: p_rn12o2=1
 integer :: p_rn12ooh=1
 integer :: p_rn13ao2=1
 integer :: p_rn13no3=1
 integer :: p_rn13o2=1
 integer :: p_rn13ooh=1
 integer :: p_rn14o2=1
 integer :: p_rn14ooh=1
 integer :: p_rn15ao2=1
 integer :: p_rn15no3=1
 integer :: p_rn15o2=1
 integer :: p_rn15ooh=1
 integer :: p_rn16ao2=1
 integer :: p_rn16no3=1
 integer :: p_rn16o2=1
 integer :: p_rn16ooh=1
 integer :: p_rn17o2=1
 integer :: p_rn17ooh=1
 integer :: p_rn18ao2=1
 integer :: p_rn18no3=1
 integer :: p_rn18o2=1
 integer :: p_rn18ooh=1
 integer :: p_rn19no3=1
 integer :: p_rn19o2=1
 integer :: p_rn19ooh=1
 integer :: p_rn8o2=1
 integer :: p_rn8ooh=1
 integer :: p_rn9no3=1
 integer :: p_rn9o2=1
 integer :: p_rn9ooh=1
 integer :: p_rno3=1
 integer :: p_ro2=1
 integer :: p_ro2_n=1
 integer :: p_ro2_r=1
 integer :: p_rooh=1
 integer :: p_ror=1
 integer :: p_rtn10o2=1
 integer :: p_rtn10ooh=1
 integer :: p_rtn14o2=1
 integer :: p_rtn14ooh=1
 integer :: p_rtn23no3=1
 integer :: p_rtn23o2=1
 integer :: p_rtn23ooh=1
 integer :: p_rtn24o2=1
 integer :: p_rtn24ooh=1
 integer :: p_rtn25no3=1
 integer :: p_rtn25o2=1
 integer :: p_rtn25ooh=1
 integer :: p_rtn26o2=1
 integer :: p_rtn26ooh=1
 integer :: p_rtn26pan=1
 integer :: p_rtn28no3=1
 integer :: p_rtn28o2=1
 integer :: p_rtn28ooh=1
 integer :: p_rtx22no3=1
 integer :: p_rtx22o2=1
 integer :: p_rtx22ooh=1
 integer :: p_rtx24no3=1
 integer :: p_rtx24o2=1
 integer :: p_rtx24ooh=1
 integer :: p_rtx28no3=1
 integer :: p_rtx28o2=1
 integer :: p_rtx28ooh=1
 integer :: p_ru10o2=1
 integer :: p_ru10ooh=1
 integer :: p_ru12o2=1
 integer :: p_ru12ooh=1
 integer :: p_ru12pan=1
 integer :: p_ru14no3=1
 integer :: p_ru14o2=1
 integer :: p_ru14ooh=1
 integer :: p_sesq=1
 integer :: p_smpa=1
 integer :: p_smpbb=1
 integer :: p_so2=5
 integer :: p_so3=1
 integer :: p_soag=1
 integer :: p_sulaer=1
 integer :: p_sulf=1
 integer :: p_tbut2ene=1
 integer :: p_tce=1
 integer :: p_tdicleth=1
 integer :: p_tepomuc=1
 integer :: p_ter=1
 integer :: p_teraer1=1
 integer :: p_teraer2=1
 integer :: p_terp=1
 integer :: p_terpaer=1
 integer :: p_terpnit=1
 integer :: p_terpo2=1
 integer :: p_terpooh=1
 integer :: p_tm123b=1
 integer :: p_tm124b=1
 integer :: p_tm135b=1
 integer :: p_tncarb10=1
 integer :: p_tncarb11=1
 integer :: p_tncarb12=1
 integer :: p_tncarb15=1
 integer :: p_tncarb26=1
 integer :: p_to2=1
 integer :: p_tol=1
 integer :: p_tolaer1=1
 integer :: p_tolaer2=1
 integer :: p_tolooh=1
 integer :: p_toluene=1
 integer :: p_tpan=1
 integer :: p_tricleth=1
 integer :: p_txcarb22=1
 integer :: p_txcarb24=1
 integer :: p_ucarb10=1
 integer :: p_ucarb12=1
 integer :: p_udcarb11=1
 integer :: p_udcarb14=1
 integer :: p_udcarb17=1
 integer :: p_udcarb8=1
 integer :: p_UDD=1
 integer :: p_voca=1
 integer :: p_vocbb=1
 integer :: p_xc=1
 integer :: p_xn=1
 integer :: p_xo2=1
 integer :: p_xo2n=1
 integer :: p_xoh=1
 integer :: p_xooh=1
 integer :: p_xpar=1
 integer :: p_xyl=1
 integer :: p_xylaer1=1
 integer :: p_xylaer2=1
 integer :: p_xylenes=1
 integer :: p_xyleno2=1
 integer :: p_xylenooh=1
 integer :: p_xylol=1
 integer :: p_xylolo2=1
 integer :: p_xylolooh=1
 integer, parameter :: CB05_SORG_AQ_KPP=131 ! Registry/registry.chem:3994
 integer, parameter :: CB05_SORG_VBS_AQ_KPP=132 ! Registry/registry.chem:3997
 integer, parameter :: CBM4_KPP=110 ! Registry/registry.chem:3981
 integer, parameter :: CBMZ=5 ! Registry/registry.chem:3931
 integer, parameter :: CBMZ_BB=6 ! Registry/registry.chem:3932
 integer, parameter :: CBMZ_BB_KPP=120 ! Registry/registry.chem:3991
 integer, parameter :: CBMZ_CAM_MAM3_AQ=503 ! Registry/registry.chem:4041
 integer, parameter :: CBMZ_CAM_MAM3_NOAQ=501 ! Registry/registry.chem:4037
 integer, parameter :: CBMZ_CAM_MAM7_AQ=504 ! Registry/registry.chem:4043
 integer, parameter :: CBMZ_CAM_MAM7_NOAQ=502 ! Registry/registry.chem:4039
 integer, parameter :: CBMZ_MOSAIC_4BIN=7 ! Registry/registry.chem:3933
 integer, parameter :: CBMZ_MOSAIC_4BIN_AQ=9 ! Registry/registry.chem:3935
 integer, parameter :: CBMZ_MOSAIC_8BIN=8 ! Registry/registry.chem:3934
 integer, parameter :: CBMZ_MOSAIC_8BIN_AQ=10 ! Registry/registry.chem:3936
 integer, parameter :: CBMZ_MOSAIC_DMS_4BIN=31 ! Registry/registry.chem:3949
 integer, parameter :: CBMZ_MOSAIC_DMS_4BIN_AQ=32 ! Registry/registry.chem:3950
 integer, parameter :: CBMZ_MOSAIC_DMS_8BIN=33 ! Registry/registry.chem:3951
 integer, parameter :: CBMZ_MOSAIC_DMS_8BIN_AQ=34 ! Registry/registry.chem:3952
 integer, parameter :: CBMZ_MOSAIC_KPP=170 ! Registry/registry.chem:4000
 integer, parameter :: cri_mosaic_4bin_aq_kpp=611 ! Registry/registry.chem:4049
 integer, parameter :: cri_mosaic_8bin_aq_kpp=601 ! Registry/registry.chem:4048
 integer, parameter :: crimech_kpp=600 ! Registry/registry.chem:4046
 integer, parameter :: GOCART_SIMPLE=300 ! Registry/registry.chem:4022
 integer, parameter :: GOCARTRACM_KPP=301 ! Registry/registry.chem:4024
 integer, parameter :: GOCARTRADM2=303 ! Registry/registry.chem:4026
 integer, parameter :: MOZART_KPP=111 ! Registry/registry.chem:3983
 integer, parameter :: MOZART_MOSAIC_4BIN_AQ_KPP=202 ! Registry/registry.chem:4010
 integer, parameter :: MOZART_MOSAIC_4BIN_KPP=201 ! Registry/registry.chem:4008
 integer, parameter :: MOZCART_KPP=112 ! Registry/registry.chem:3986
 integer, parameter :: RACM_SOA_VBS_AQCHEM_KPP=109 ! Registry/registry.chem:3979
 integer, parameter :: RACM_SOA_VBS_HET_KPP=100 ! Registry/registry.chem:3977
 integer, parameter :: RACM_SOA_VBS_KPP=108 ! Registry/registry.chem:3975
 integer, parameter :: RADM2=1 ! Registry/registry.chem:3929
 integer, parameter :: RADM2SORG=2 ! Registry/registry.chem:3930
 integer, parameter :: RADM2SORG_AQ=11 ! Registry/registry.chem:3938
 integer, parameter :: RADM2SORG_AQCHEM=41 ! Registry/registry.chem:3955
 integer, parameter :: T1_MOZCART_KPP=114 ! Registry/registry.chem:3989
end module
module module_configure
 implicit none
 type grid_config_rec_type
  integer :: chem_opt=300,num_land_cat=25
  real :: depo_fact=1.
 end type
contains
 subroutine nl_get_sf_surface_physics(id,value)
 integer,intent(in)::id
 integer,intent(out)::value
 value=2
 end subroutine
 subroutine nl_get_max_dom(id,value)
 integer,intent(in)::id
 integer,intent(out)::value
 value=1
 end subroutine
end module
module module_data_sorgam
end module
module module_scalar_tables
 character(len=64) :: chem_dname_table(1,9)=''
end module
module module_chem_utilities
contains
 subroutine upcase(s)
 character(len=*),intent(inout)::s
 error stop 'unexercised MOZART service upcase'
 end subroutine
end module
module module_HLawConst
 integer,parameter :: nHLC=0
 type HL_entry
 character(len=64) :: name
 end type
 type(HL_entry) :: HLC(0)
end module
subroutine wrf_debug(level,message)
 integer,intent(in)::level
 character(len=*),intent(in)::message
end subroutine
subroutine wrf_abort
 error stop 'wrf_abort'
end subroutine
