"""Which surface-observation networks cover a domain, anywhere on Earth.

``rw_asos`` was already worldwide: its archive URL, its ``--networks`` list
and its ``--bbox`` are all arguments, and the network id is concatenated into
a URL template rather than branched on. What was missing was the step before
it -- given a domain, *which* networks to name. Passing the wrong ones is not
an error anyone sees: the fetch succeeds, the station table comes back short
or empty, and the case is scored against fewer observations than exist.

So this module owns one question and answers it from a frozen table:

    networks_for_bbox(west, south, east, north) -> ("DE__ASOS", "CZ__ASOS", ...)

**The extent is a candidate screen, not the filter.** Each row carries the
bounding box the archive publishes for that network, and that box is the
archive's own claim, padded and sometimes stale -- one European network
declares a southern edge in the tropics. Measured on 2026-08-12 against the
live station lists of twelve networks across three continents, every declared
extent *contained* its stations, with the archive padding each edge by 0.1
deg. So the screen errs toward including a network whose stations turn out to
lie elsewhere, and never toward dropping one.

That direction is the one that matters and it is load-bearing. Including a
network that contributes nothing costs one metadata request. Dropping one
costs observations, silently. The authoritative filter is the station-level
``--bbox`` that ``rw_asos stations`` already applies to real station
coordinates; this module's job is only to make sure the right networks were
offered to it.

Nothing here names a country in code. Network ids and their boxes are data in
``data/surface_networks.json``, regenerated by
``tools/freeze_surface_networks.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import json
from pathlib import Path

#: The schema the frozen table must declare.
TABLE_SCHEMA = "gpuwm-obs.surface-networks.v1"

#: Where the frozen table lives, beside this module.
TABLE_PATH = Path(__file__).resolve().parent / "data" / "surface_networks.json"


class SurfaceNetworkError(RuntimeError):
    """The network table cannot answer, and the reason is the message."""


@dataclass(frozen=True)
class SurfaceNetwork:
    """One network the archive holds, and where its stations actually are.

    ``east`` may exceed ``+180``. That is not a coordinate error: a network
    whose stations straddle the antimeridian has no representation as a
    single ``west <= east`` interval inside ``[-180, 180]``, and the
    alternative -- ``min``/``max`` over the raw longitudes -- produces a box
    spanning nearly the whole globe. New Zealand reports stations near +178
    and near -176, so that box would be ``[-176, 178]`` and would match
    domains in the South Atlantic. The interval is stored as the shortest one
    that contains every station, running past +180 when it must, and
    :meth:`intersects` reads it in both pieces.
    """

    id: str
    name: str
    west: float
    south: float
    east: float
    north: float
    #: How many stations the extent was measured over, when the table records
    #: it. Carried for the receipt, never for the screen.
    stations: int | None = None

    @property
    def crosses_antimeridian(self) -> bool:
        return self.east > 180.0

    def _longitude_pieces(self) -> tuple[tuple[float, float], ...]:
        """The extent's longitude interval(s) inside ``[-180, 180]``."""

        if not self.crosses_antimeridian:
            return ((self.west, self.east),)
        return ((self.west, 180.0), (-180.0, self.east - 360.0))

    def intersects(self, west: float, south: float, east: float,
                   north: float) -> bool:
        """Does this network's extent overlap the box at all?

        Touching counts. A domain whose edge grazes a network's edge may
        still hold one of its stations, and the station-level filter is what
        decides that; excluding on a shared boundary here would drop the
        chance to ask.
        """

        if self.north < south or self.south > north:
            return False
        return any(not (piece_east < west or piece_west > east)
                   for piece_west, piece_east in self._longitude_pieces())


@dataclass(frozen=True)
class SurfaceNetworkTable:
    """The frozen table, with the provenance of the listing it came from."""

    schema: str
    source_url: str
    source_sha256: str
    frozen_at: str
    networks: tuple[SurfaceNetwork, ...]

    def __len__(self) -> int:
        return len(self.networks)


def _load(path: Path) -> SurfaceNetworkTable:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as error:
        raise SurfaceNetworkError(
            f"cannot read the surface-network table at {path}: {error}. "
            f"Regenerate it with tools/freeze_surface_networks.py") from error
    try:
        document = json.loads(raw)
    except json.JSONDecodeError as error:
        raise SurfaceNetworkError(
            f"{path} is not JSON: {error}") from error
    schema = str(document.get("schema", ""))
    if schema != TABLE_SCHEMA:
        raise SurfaceNetworkError(
            f"{path} declares schema {schema!r}, expected {TABLE_SCHEMA!r}")
    rows = document.get("networks") or ()
    if not rows:
        raise SurfaceNetworkError(
            f"{path} lists no networks; an empty table resolves every domain "
            f"to no observations, which is indistinguishable from a domain "
            f"the archive genuinely does not cover")
    networks = []
    seen: set[str] = set()
    for row in rows:
        network = str(row["id"])
        if network in seen:
            raise SurfaceNetworkError(
                f"{path} lists network {network!r} twice; which extent is "
                f"the network's would then be an ordering accident")
        seen.add(network)
        stations = row.get("stations")
        entry = SurfaceNetwork(
            id=network,
            name=str(row.get("name", "")),
            west=float(row["west"]),
            south=float(row["south"]),
            east=float(row["east"]),
            north=float(row["north"]),
            stations=None if stations is None else int(stations),
        )
        if not (-90.0 <= entry.south <= entry.north <= 90.0):
            raise SurfaceNetworkError(
                f"{path}: network {network!r} spans latitudes "
                f"[{entry.south}, {entry.north}], which is not a band on the "
                f"globe")
        if not (-180.0 <= entry.west <= entry.east <= 540.0):
            raise SurfaceNetworkError(
                f"{path}: network {network!r} spans longitudes "
                f"[{entry.west}, {entry.east}]; an extent runs west to east "
                f"and may pass +180 once, never further")
        networks.append(entry)
    networks.sort(key=lambda entry: entry.id)
    return SurfaceNetworkTable(
        schema=schema,
        source_url=str(document.get("source_url", "")),
        source_sha256=str(document.get("source_sha256", "")),
        frozen_at=str(document.get("frozen_at", "")),
        networks=tuple(networks),
    )


@lru_cache(maxsize=4)
def load_table(path: str | Path | None = None) -> SurfaceNetworkTable:
    """The frozen network table, read once per path."""

    return _load(Path(path) if path is not None else TABLE_PATH)


def _check_box(west: float, south: float, east: float,
               north: float) -> tuple[float, float, float, float]:
    values = (float(west), float(south), float(east), float(north))
    if not all(value == value and abs(value) != float("inf")
               for value in values):
        raise SurfaceNetworkError("a domain box must be four finite numbers")
    if south >= north:
        raise SurfaceNetworkError(
            f"domain south {south} is not below north {north}")
    if west >= east:
        raise SurfaceNetworkError(
            f"domain west {west} is not west of east {east}; a box that "
            f"crosses the antimeridian is not supported, and silently "
            f"wrapping one would resolve the wrong hemisphere")
    if south < -90.0 or north > 90.0:
        raise SurfaceNetworkError("domain latitudes must lie inside [-90, 90]")
    if west < -180.0 or east > 180.0:
        raise SurfaceNetworkError(
            "domain longitudes must lie inside [-180, 180]")
    return values


def networks_for_bbox(west: float, south: float, east: float, north: float, *,
                      table: SurfaceNetworkTable | None = None,
                      ) -> tuple[str, ...]:
    """Every network whose declared extent overlaps the domain, sorted by id.

    Sorted rather than in table order so the same domain names the same
    networks in the same sequence on every host: the id list ends up in a
    receipt, and a set that reorders itself makes two identical runs look
    different.

    Raises :class:`SurfaceNetworkError` when nothing overlaps. A domain the
    archive does not cover is a real answer, but it is not the same answer as
    an empty fetch, and returning an empty tuple would let a case run to
    completion having assimilated no surface observation and said nothing
    about it.
    """

    west, south, east, north = _check_box(west, south, east, north)
    table = table or load_table()
    matched = tuple(
        network.id for network in table.networks
        if network.intersects(west, south, east, north))
    if not matched:
        raise SurfaceNetworkError(
            f"none of the {len(table)} networks in the surface table has an "
            f"extent overlapping ({west:g}, {south:g}, {east:g}, {north:g}). "
            f"This domain has no surface observations from this archive; "
            f"refusing rather than returning an empty list, because a run "
            f"that assimilated nothing and reported nothing looks exactly "
            f"like a run that assimilated everything")
    return matched


def describe(networks: tuple[str, ...] | list[str], *,
             table: SurfaceNetworkTable | None = None) -> tuple[str, ...]:
    """``("DE__ASOS (Germany ASOS)", ...)`` for a receipt or a log line."""

    table = table or load_table()
    names = {network.id: network.name for network in table.networks}
    return tuple(
        f"{network} ({names[network]})" if names.get(network) else str(network)
        for network in networks)


__all__ = ["SurfaceNetwork", "SurfaceNetworkError", "SurfaceNetworkTable",
           "TABLE_PATH", "TABLE_SCHEMA", "describe", "load_table",
           "networks_for_bbox"]
