#!/usr/bin/env python3
"""Prove the exact Python distributions and bridge assets before publishing.

Run this script with the newly built wheel installed into an isolated virtual
environment and Python ``-I`` from outside the checkout.  It intentionally
uses the installed package's production parsers, staging path, executable
probes, and CPU-library ABI check.  The checkout supplies only this verifier
and the expected artifacts.
"""

from __future__ import annotations

import argparse
from base64 import urlsafe_b64encode
import csv
import ctypes
import hashlib
import io
import json
from pathlib import Path
import tarfile
from types import SimpleNamespace
import zipfile


_PINS_MEMBER = "gpuwm/data/bridges/bridge-pins.json"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel", type=Path, required=True)
    parser.add_argument("--sdist", type=Path, required=True)
    parser.add_argument("--pins", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--bundles", type=Path, required=True)
    parser.add_argument("--release", required=True)
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--stage", type=Path, required=True)
    parser.add_argument("--receipt", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    wheel = args.wheel.resolve(strict=True)
    sdist = args.sdist.resolve(strict=True)
    pins_path = args.pins.resolve(strict=True)
    manifest_path = args.manifest.resolve(strict=True)
    bundles = args.bundles.resolve(strict=True)
    repo = args.repo_root.resolve(strict=True)
    stage = args.stage.resolve()
    receipt_path = args.receipt.resolve()

    expected_pins = pins_path.read_bytes()
    pins_document = json.loads(expected_pins)
    manifest_document = json.loads(manifest_path.read_bytes())
    assert pins_document["schema"] == "gpuwm-bridge-pins-v1"
    assert manifest_document["schema"] == "gpuwm-bridge-bundle-manifest-v1"
    assert pins_document["release"] == args.release
    assert manifest_document["release"] == args.release
    assert manifest_document["platforms"] == pins_document["platforms"]

    # The wheel carries the exact generated bytes, and RECORD binds their hash
    # and size rather than merely naming the member.
    with zipfile.ZipFile(wheel) as archive:
        assert archive.namelist().count(_PINS_MEMBER) == 1
        assert archive.read(_PINS_MEMBER) == expected_pins
        records = [
            name for name in archive.namelist() if name.endswith(".dist-info/RECORD")
        ]
        assert len(records) == 1, records
        rows = [
            row
            for row in csv.reader(
                io.StringIO(archive.read(records[0]).decode("utf-8"))
            )
            if row and row[0] == _PINS_MEMBER
        ]
        assert len(rows) == 1, rows
        digest = urlsafe_b64encode(hashlib.sha256(expected_pins).digest()).rstrip(
            b"="
        ).decode("ascii")
        assert rows[0][1] == f"sha256={digest}", rows[0]
        assert rows[0][2] == str(len(expected_pins)), rows[0]

    # PyPI publishes the sdist too, so it must carry the identical pins.
    with tarfile.open(sdist, "r:gz") as archive:
        members = [
            member
            for member in archive.getmembers()
            if member.name.endswith("/" + _PINS_MEMBER)
        ]
        assert len(members) == 1, [member.name for member in members]
        source = archive.extractfile(members[0])
        assert source is not None
        assert source.read() == expected_pins

    # Under ``python -I`` these resolve from the clean wheel installation, not
    # the checkout beside the verifier.
    import gpuwm
    from gpuwm import bridge_assets, bridges, doctor

    installed = Path(gpuwm.__file__).resolve()
    assert not installed.is_relative_to(repo), installed
    assert args.release == f"v{gpuwm.__version__}", (
        args.release,
        gpuwm.__version__,
    )
    assert bridge_assets.packaged_pins_path().read_bytes() == expected_pins

    pins = bridge_assets.load_pins()
    assert pins.release == args.release, pins.release
    assert set(pins.platforms) == set(bridge_assets.SUPPORTED_PLATFORMS)
    assert len(pins.platforms) == 2

    by_name = {
        artifact.name: artifact for artifact in bridge_assets.BUNDLED_ARTIFACTS
    }
    bundle_receipts: dict[str, object] = {}
    for platform, bundle in sorted(pins.platforms.items()):
        assert len(bundle.binaries) == len(by_name) == 8
        assert {pin.artifact for pin in bundle.binaries} == set(by_name)
        archive_path = bundles / bundle.filename
        bridge_assets.verify_pinned_file(
            archive_path,
            expected_bytes=bundle.bytes,
            expected_sha256=bundle.sha256,
            label=bundle.filename,
        )
        # A bundle carries the eight binaries AND the renderer's map assets --
        # that is the whole point of the asset half, since a bridge binary
        # without its basemaps draws weather over a blank rectangle.  This
        # membership test predates the assets and compared against the binary
        # pins alone, so it refused every bundle the current packer produces.
        # It is not enough to widen it to "at least the binaries": a bundle
        # must contain exactly what the release pinned and nothing else, so
        # both halves are named and the equality is kept.
        assert bundle.assets, (platform, "bundle pins no map assets")
        expected_members = (
            {pin.filename for pin in bundle.binaries}
            | {pin.path for pin in bundle.assets}
        )
        with zipfile.ZipFile(archive_path) as archive:
            members = set(archive.namelist())
            assert members == expected_members, (
                platform,
                f"unexpected: {sorted(members - expected_members)}",
                f"missing: {sorted(expected_members - members)}",
            )
            for pin in bundle.binaries:
                payload = archive.read(pin.filename)
                assert len(payload) == pin.bytes, (platform, pin.filename)
                assert hashlib.sha256(payload).hexdigest() == pin.sha256, (
                    platform, pin.filename)
            for pin in bundle.assets:
                payload = archive.read(pin.path)
                assert len(payload) == pin.bytes, (platform, pin.path)
                assert hashlib.sha256(payload).hexdigest() == pin.sha256, (
                    platform, pin.path)
        bundle_receipts[platform] = {
            "filename": bundle.filename,
            "bytes": bundle.bytes,
            "sha256": bundle.sha256,
            "members": len(bundle.binaries) + len(bundle.assets),
            "binaries": len(bundle.binaries),
            "assets": len(bundle.assets),
        }

    offer = bridges.prebuilt_bundle_offer()
    assert offer is not None
    live = [
        line.strip()
        for line in offer
        if line.strip() and not line.lstrip().startswith("#")
    ]
    assert live == ["gpuwm fetch-bridges"], live

    if stage.exists():
        assert not any(stage.iterdir()), stage
    fetch_args = SimpleNamespace(
        dest=str(stage), from_dir=str(bundles), list=False, keep_bundle=False
    )
    assert bridge_assets.fetch_bridges_main(fetch_args) == 0
    host = bridge_assets.host_platform()
    host_bundle = pins.bundle_for(host)
    assert host_bundle is not None
    probes: list[dict[str, object]] = []
    for pin in host_bundle.binaries:
        path = stage / pin.filename
        assert bridge_assets.matches_pin(path, pin), path
        artifact = by_name[pin.artifact]
        if artifact.kind == "executable":
            ok, evidence = doctor._exec_probe(path)
            assert ok, (path, evidence)
            probes.append(
                {
                    "artifact": artifact.name,
                    "filename": pin.filename,
                    "kind": artifact.kind,
                    "evidence": evidence,
                    "status": "PASS",
                }
            )
        else:
            library = ctypes.CDLL(str(path))
            abi = library.gpuwm_preprocess_cpu_abi_version
            abi.argtypes = []
            abi.restype = ctypes.c_uint32
            assert int(abi()) == 1
            probes.append(
                {
                    "artifact": artifact.name,
                    "filename": pin.filename,
                    "kind": artifact.kind,
                    "abi": 1,
                    "status": "PASS",
                }
            )

    receipt = {
        "schema": "gpuwm-release-artifact-proof-v1",
        "status": "PASS",
        "release": args.release,
        "installed_module": str(installed),
        "installed_version": gpuwm.__version__,
        "wheel": {
            "filename": wheel.name,
            "bytes": wheel.stat().st_size,
            "sha256": _sha256(wheel),
            "pins_bytes_exact": True,
            "record_digest_and_size_exact": True,
        },
        "sdist": {
            "filename": sdist.name,
            "bytes": sdist.stat().st_size,
            "sha256": _sha256(sdist),
            "pins_bytes_exact": True,
        },
        "pins": {
            "filename": pins_path.name,
            "bytes": pins_path.stat().st_size,
            "sha256": _sha256(pins_path),
        },
        "manifest": {
            "filename": manifest_path.name,
            "bytes": manifest_path.stat().st_size,
            "sha256": _sha256(manifest_path),
            "platforms_exactly_match_pins": True,
        },
        "bundles": bundle_receipts,
        "prebuilt_offer_live_lines": live,
        "host_platform": host,
        "host_probes": probes,
    }
    receipt_path.parent.mkdir(parents=True, exist_ok=True)
    receipt_path.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(receipt, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
